import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import {MAX_UNITS,newPlayerWallet,availableUnits,planManualAdjustment,assertApprovedSlotDecision} from './product-policy.mjs';
const decisions=JSON.parse(readFileSync(new URL('../config/product-decisions.json',import.meta.url),'utf8'));
const request=()=>({principal:{id:'admin-1',role:'MAIN_ADMIN',active:true,stepUpVerified:true},wallet:{id:'player-1',settledUnits:10000n,reservedUnits:2000n,version:7},direction:'ADD',amountUnits:2500n,reason:'Owner-approved manual adjustment',idempotencyKey:'request-0001',expectedWalletVersion:7});
function throwsCode(fn,code){assert.throws(fn,e=>e.code===code);}
test('new player is zero with no automatic reserve',()=>assert.deepEqual(newPlayerWallet('p'),{id:'p',settledUnits:0n,reservedUnits:0n,version:0}));
test('all grant/refill flags disabled in v2 decisions',()=>{for(const k of ['automaticGrants','scheduledGrants','welcomeGrants','dailyRewards','automaticRefills','promotionalGrants'])assert.equal(decisions.credits[k],false);assert.equal(decisions.credits.initialPlayerBalanceUnits,'0');});
test('ordinary game settlement remains permitted, distinct from grants',()=>assert.equal(decisions.credits.gameSettlementCredits,true));
test('Android and iOS both required',()=>{assert.equal(decisions.platforms.android,true);assert.equal(decisions.platforms.ios,true);});
test('owner-approved branch transfers have an explicit implemented permission matrix',()=>{assert.equal(decisions.credits.lowerTierTransfers,'APPROVED_BRANCH_EXISTING_CREDITS');assert.equal(decisions.credits.transferImplementation,'ENABLED_SELF_TO_LOWER_BRANCH_ROLES');});
test('admin ADD proposes balanced exact postings and expected new amount',()=>{const p=planManualAdjustment(request());assert.equal(p.afterUnits,'12500');assert.equal(p.availableAfterUnits,'10500');assert.equal(p.entries.reduce((s,e)=>s+BigInt(e.changeUnits),0n),0n);assert.equal(p.status,'PROPOSED_NOT_COMMITTED');});
test('admin REMOVE uses available credits without taking a reserve',()=>{const p=planManualAdjustment({...request(),direction:'REMOVE',amountUnits:3000n});assert.equal(p.afterUnits,'7000');assert.equal(p.availableAfterUnits,'5000');assert.equal(p.reservedUnits,'2000');});
test('remove beyond available is rejected even below settled total',()=>throwsCode(()=>planManualAdjustment({...request(),direction:'REMOVE',amountUnits:9000n}),'INSUFFICIENT_AVAILABLE'));
test('remove exactly available preserves the reserved amount',()=>{const p=planManualAdjustment({...request(),direction:'REMOVE',amountUnits:8000n});assert.equal(p.afterUnits,'2000');assert.equal(p.availableAfterUnits,'0');});
test('all lower roles are denied adjustment even with a forged step-up flag',()=>{for(const role of ['SUB_DISTRIBUTOR','AGENT','PLAYER','MAIN_DISTRIBUTOR'])throwsCode(()=>planManualAdjustment({...request(),principal:{...request().principal,role}}),'FORBIDDEN');});
test('inactive root is denied',()=>throwsCode(()=>planManualAdjustment({...request(),principal:{...request().principal,active:false}}),'FORBIDDEN'));
test('root requires trusted step-up claim',()=>throwsCode(()=>planManualAdjustment({...request(),principal:{...request().principal,stepUpVerified:false}}),'STEP_UP_REQUIRED'));
test('reason must be meaningful and bounded',()=>{for(const reason of ['', '    ','a'.repeat(501)])throwsCode(()=>planManualAdjustment({...request(),reason}),'REASON_REQUIRED');});
test('idempotency key is mandatory but helper does not persist it',()=>throwsCode(()=>planManualAdjustment({...request(),idempotencyKey:''}),'BAD_IDEMPOTENCY_KEY'));
test('stale preview fails',()=>throwsCode(()=>planManualAdjustment({...request(),expectedWalletVersion:6}),'STALE_WALLET'));
test('negative zero float and oversized amounts fail',()=>{for(const amountUnits of [0n,-1n,2.5,MAX_UNITS+1n])throwsCode(()=>planManualAdjustment({...request(),amountUnits}),'BAD_AMOUNT');});
test('addition overflow fails rather than wrapping',()=>throwsCode(()=>planManualAdjustment({...request(),wallet:{...request().wallet,settledUnits:MAX_UNITS},amountUnits:1n}),'BALANCE_OVERFLOW'));
test('invalid reserve state rejected',()=>throwsCode(()=>availableUnits({settledUnits:1n,reservedUnits:2n}),'BAD_RESERVED'));
test('no direct set-balance command',()=>throwsCode(()=>planManualAdjustment({...request(),direction:'SET'}),'BAD_DIRECTION'));
test('planning helper does not mutate wallet data',()=>{const r=request();const before={...r.wallet};planManualAdjustment(r);assert.deepEqual(r.wallet,before);});
test('pending shipped slot record fails closed',()=>{assert.equal(decisions.slotMath.approvedProfileId,null);throwsCode(()=>assertApprovedSlotDecision(decisions.slotMath),'SLOT_MATH_NOT_APPROVED');});
test('complete illustrative approval record validates structurally, not cryptographically',()=>assert.equal(assertApprovedSlotDecision({status:'APPROVED',metric:'HIT_RATE',targetHitRate:.3,approvedProfileId:'fixture-only',approvedMathHash:'a'.repeat(64),approvalRef:'fixture-owner-ref'}),'fixture-only'));
test('approval status alone does not enable a slot',()=>throwsCode(()=>assertApprovedSlotDecision({status:'APPROVED'}),'METRIC_REQUIRED'));
test('approval with missing target rejected',()=>throwsCode(()=>assertApprovedSlotDecision({status:'APPROVED',metric:'RTP',approvedProfileId:'fixture',approvedMathHash:'a'.repeat(64),approvalRef:'fixture'}),'TARGET_REQUIRED'));
