<script setup lang="ts">
import { computed,onMounted,ref } from 'vue';
import Icon from '@new-game/ui/Icon.vue';
import { formatCredits,parseCredits } from '@new-game/domain';
import { api,signIn,refreshAccount,session,expiredSession,type Account } from '../../player/src/api';
type Member=Omit<Account,'csrf'> & {branch:string;active:boolean};
type Entry={id:string;kind:string;units:string;before_units:string;after_units:string;reason:string;actor:string;created_at:string};
const current=ref<Account|null>(null),members=ref<Member[]>([]),selectedId=ref(''),query=ref(''),page=ref('Accounts');
const username=ref(''),password=ref(''),code=ref(''),error=ref(''),busy=ref(false);
const selected=computed(()=>members.value.find(a=>a.id===selectedId.value));
const filtered=computed(()=>members.value.filter(a=>`${a.displayName} ${a.username} ${a.branch}`.toLowerCase().includes(query.value.toLowerCase())));
const history=ref<Entry[]>([]),totals=ref<{kind:string;transactions:string;positive_units:string}[]>([]);
const dialog=ref(false),direction=ref<'ADD'|'REMOVE'|'TRANSFER'>('ADD'),amount=ref(''),reason=ref(''),review=ref(false),receipt=ref('');
const request=ref<Record<string,string>|null>(null),after=ref('0'),units=ref('0');
const createOpen=ref(false),parentId=ref(''),newName=ref(''),newUsername=ref(''),newPassword=ref('');
const verifyOpen=ref(false),verifyPassword=ref(''),verifyCode=ref('');
const manageOpen=ref(false),resetPassword=ref(''),manageReason=ref('');
const auditRows=ref<{id:string;event_type:string;actor:string;created_at:string}[]>([]);
async function manage(action:'RESET_PASSWORD'|'SET_ACTIVE'){if(!selected.value)return;await run(async()=>{await api(`admin/accounts/${selected.value!.id}/manage`,{action,reason:manageReason.value,...(action==='RESET_PASSWORD'?{password:resetPassword.value}:{active:!selected.value!.active})});manageOpen.value=false;resetPassword.value='';manageReason.value='';await load();});}
async function showAudit(){page.value='Audit log';await run(async()=>{auditRows.value=await api<typeof auditRows.value>('admin/audit');});}
async function run(work:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';try{await work();}catch(e){error.value=(e as Error).message;if(expiredSession(e)){current.value=null;session.current=null;dialog.value=false;createOpen.value=false;manageOpen.value=false;verifyOpen.value=false;}else if(error.value.includes('Verify your password'))verifyOpen.value=true;}finally{busy.value=false;}}
async function load(){current.value=await refreshAccount();if(current.value.role==='PLAYER'){current.value=null;throw new Error('Player accounts use the arcade login.');}members.value=await api<Member[]>('admin/accounts');if(!selectedId.value)selectedId.value=members.value.find(a=>a.role==='PLAYER')?.id||members.value[0]?.id||'';parentId.value ||=current.value.id;await loadHistory();totals.value=await api<typeof totals.value>('admin/report');}
async function loadHistory(){if(selectedId.value)history.value=await api<Entry[]>(`history?accountId=${selectedId.value}`);}
async function login(){await run(async()=>{await signIn(username.value,password.value,code.value);password.value='';code.value='';await load();});}
async function logout(){await run(async()=>{await api('auth/logout',{});current.value=null;session.current=null;members.value=[];});}
function choose(id:string){selectedId.value=id;void run(loadHistory);}
function open(value:'ADD'|'REMOVE'|'TRANSFER'){direction.value=value;amount.value='';reason.value='';error.value='';receipt.value='';review.value=false;request.value=null;dialog.value=true;}
function preview(){try{if(!selected.value||!current.value)return;if(reason.value.trim().length<5)throw new Error('Enter a meaningful reason of at least 5 characters.');units.value=parseCredits(amount.value);const wallet=selected.value.wallet;const source=direction.value==='TRANSFER'?current.value.wallet:wallet;if(direction.value!=='ADD'&&BigInt(units.value)>BigInt(source.available))throw new Error('Only available credits can be removed or transferred.');after.value=(BigInt(wallet.settled)+(direction.value==='REMOVE'?-1n:1n)*BigInt(units.value)).toString();request.value={targetId:selected.value.id,amount:units.value,reason:reason.value.trim(),requestKey:crypto.randomUUID(),expectedVersion:source.version,...(direction.value==='TRANSFER'?{targetVersion:wallet.version}:{direction:direction.value})};review.value=true;error.value='';}catch(e){error.value=(e as Error).message;}}
async function confirm(){await run(async()=>{const result=await api<{id:string}>(direction.value==='TRANSFER'?'credit-transfers':'admin/credit-adjustments',request.value);receipt.value=result.id;await load();});}
async function create(){await run(async()=>{await api('admin/accounts',{parentId:parentId.value,username:newUsername.value,displayName:newName.value,password:newPassword.value});newPassword.value='';newUsername.value='';newName.value='';createOpen.value=false;await load();});}
async function verify(){await run(async()=>{await api('auth/verify',{password:verifyPassword.value,code:verifyCode.value});verifyPassword.value='';verifyCode.value='';verifyOpen.value=false;});}
onMounted(async()=>{try{await load();}catch{/* Login is shown when no valid staff session exists. */}});
</script>
<template>
 <main v-if="!current" class="staff-login"><div class="staff-login-card"><span class="eyebrow">NEW GAME · OPERATOR CONSOLE</span><h1>Welcome back.</h1><p>Sign in to manage your private arcade.</p><form @submit.prevent="login"><label for="staff-user">Staff ID</label><input id="staff-user" v-model="username" autocomplete="username" required><label for="staff-pass">Password</label><input id="staff-pass" v-model="password" type="password" autocomplete="current-password" required><label for="staff-code">Authenticator code <small>(Main Admin)</small></label><input id="staff-code" v-model="code" inputmode="numeric" autocomplete="one-time-code" maxlength="6"><p v-if="error" role="alert" class="error">{{error}}</p><button class="primary" :disabled="busy">{{busy?'Signing in…':'Sign in'}}</button></form><small>Private play credits. No purchases or cash-out.</small></div></main>
 <div v-else class="admin-shell"><aside class="admin-sidebar"><div class="admin-brand"><span>N</span><strong>new game.</strong></div><span class="eyebrow admin-label">Operator console</span><nav><button v-for="item in ['Accounts','Overview','Organization','Credit history']" :key="item" :class="{active:page===item}" @click="page=item"><Icon :name="item==='Accounts'?'user':item==='Overview'?'grid':item==='Organization'?'shield':'clock'"/>{{item}}</button><button v-if="current.role==='MAIN_ADMIN'" @click="showAudit"><Icon name="shield"/>Audit log</button></nav><div class="admin-identity"><div class="staff-avatar">{{current.displayName.slice(0,2).toUpperCase()}}</div><span>{{current.displayName}}<small>{{current.role}}</small></span></div></aside>
 <div class="admin-workspace"><header class="admin-header"><span>Workspace <i>/</i> <strong>{{page}}</strong></span><button class="secondary" :disabled="busy" @click="run(load)">Refresh</button><button class="secondary" :disabled="busy" @click="logout">Sign out</button></header><main class="admin-main"><div class="admin-page-title"><div><span class="eyebrow">Your private group</span><h1>{{page==='Accounts'?'People & play credits':page}}</h1><p>Persistent accounts, branch access and traceable credit movements.</p></div><button v-if="current.role==='MAIN_ADMIN'" class="primary" @click="createOpen=true">Create account</button></div><p v-if="error&&!dialog&&!createOpen&&!verifyOpen" class="error" role="alert">{{error}}</p>
 <section v-if="page==='Accounts'" class="account-layout"><div class="account-list"><div class="panel-title"><h2>Accounts</h2><span>{{members.length}}</span></div><label class="admin-search"><Icon name="search" :size="17"/><input v-model="query" placeholder="Find an account or branch" aria-label="Search accounts"></label><button v-for="member in filtered" :key="member.id" class="player-row" :class="{selected:selectedId===member.id}" @click="choose(member.id)"><span class="person-avatar">{{member.displayName.slice(0,2).toUpperCase()}}</span><span><strong>{{member.displayName}}</strong><small>@{{member.username}} · {{member.role}}</small></span></button></div>
 <div v-if="selected" class="account-detail"><div class="detail-identity"><span class="person-avatar large">{{selected.displayName.slice(0,2).toUpperCase()}}</span><div><h2>{{selected.displayName}}</h2><p>@{{selected.username}} · {{selected.role}}</p></div><span class="pill">{{selected.active?'ACTIVE':'INACTIVE'}}</span></div><div class="branch-path"><Icon name="shield" :size="15"/>{{selected.branch}}</div><div class="balance-panel"><div><span class="eyebrow">Available to play</span><strong>{{formatCredits(selected.wallet.available)}}</strong><small>play credits</small></div><div class="balance-split"><p>Settled <b>{{formatCredits(selected.wallet.settled)}}</b></p><p>Reserved <b>{{formatCredits(selected.wallet.reserved)}}</b></p><p>Wallet version <b>{{selected.wallet.version}}</b></p></div></div><div class="credit-actions"><template v-if="current.role==='MAIN_ADMIN'"><button class="primary" @click="open('ADD')"><Icon name="plus" :size="17"/>Add credits</button><button class="secondary" @click="open('REMOVE')"><Icon name="minus" :size="17"/>Remove credits</button></template><button v-if="selected.id!==current.id && selected.role!=='MAIN_ADMIN'" class="secondary" @click="open('TRANSFER')">Transfer my credits</button></div><button v-if="current.role === 'MAIN_ADMIN' && selected.role !== 'MAIN_ADMIN'" class="secondary manage-account" @click="manageOpen=true; error=''">Manage account access</button><p class="manual-note"><Icon name="info" :size="15"/>Only Main Admin issues or removes supply. Transfers move your own available credits.</p><div class="detail-section-title"><h3>Recent credit activity</h3><span>{{history.length}} entries</span></div><div v-if="!history.length" class="detail-empty"><Icon name="wallet" :size="26"/><h3>No activity yet</h3><p>Every account starts at zero.</p></div><article v-for="entry in history" :key="entry.id" class="ledger-row"><div><b>{{entry.kind}}</b><p>{{entry.reason}}</p><small>{{entry.actor}} · {{new Date(entry.created_at).toLocaleString()}}</small></div><strong>{{formatCredits(entry.units)}}</strong></article><div class="account-id">ACCOUNT ID <code>{{selected.id}}</code></div></div></section>
 <template v-else-if="page==='Overview'"><div class="stat-grid"><article><small>Accounts in your branch</small><strong>{{members.length}}</strong><span>{{members.filter(m=>m.role==='PLAYER').length}} players</span></article><article v-for="row in totals" :key="row.kind"><small>{{row.kind}}</small><strong>{{formatCredits(row.positive_units)}}</strong><span>{{row.transactions}} transactions</span></article></div><div class="status-note">Credit-staked games remain closed until approved math profiles exist. Practice activity has no credit flow. Manual changes and transfers are separate from game stakes and awards.</div></template>
 <section v-else-if="page==='Organization'" class="org-panel"><h2>Your branch</h2><p>Only accounts in your authorized subtree are returned by the server.</p><article v-for="member in members" :key="member.id" class="ledger-row"><div><strong>{{member.displayName}}</strong><p>{{member.branch}}</p></div><span>{{member.role}}</span></article></section>
 <section v-else-if="page === 'Audit log'" class="org-panel"><h2>Immutable audit history</h2><article v-for="entry in auditRows" :key="entry.id" class="ledger-row"><div><b>{{entry.event_type}}</b><p>{{entry.actor}} · {{new Date(entry.created_at).toLocaleString()}}</p><small>{{entry.id}}</small></div></article></section><section v-else class="org-panel"><h2>{{selected?.displayName}} · Credit history</h2><p v-if="!history.length">No committed transactions for this account.</p><article v-for="entry in history" :key="entry.id" class="ledger-row"><div><b>{{entry.kind}}</b><p>{{entry.reason}}</p><small>{{entry.id}}</small></div><strong>{{formatCredits(entry.units)}}</strong></article></section>
 <footer class="admin-footer">New Game · Private operator console<span>Play credits only. No purchases, cash-out, or prizes of value.</span></footer></main></div>
 <div v-if="dialog&&selected" class="modal-backdrop"><section class="modal adjustment-modal" role="dialog" aria-modal="true" aria-labelledby="adjustment-title"><header><div><span class="eyebrow">{{receipt?'Committed receipt':review?'Review before confirming':'Manual credit action'}}</span><h2 id="adjustment-title">{{direction==='ADD'?'Add credits':direction==='REMOVE'?'Remove credits':'Transfer credits'}}</h2></div><button class="icon-button" aria-label="Close adjustment" :disabled="busy" @click="dialog=false"><Icon name="close"/></button></header><div class="adjustment-target"><strong>{{selected.displayName}}</strong><small>{{selected.branch}}</small></div><p v-if="error" class="error" role="alert">{{error}}</p><template v-if="receipt"><div class="status-note">Saved successfully. Receipt <code>{{receipt}}</code></div><p>The updated wallet and immutable history are now available.</p><button class="primary" @click="dialog=false">Done</button></template><form v-else-if="!review" @submit.prevent="preview"><label for="amount">Amount in play credits</label><input id="amount" v-model="amount" inputmode="decimal" placeholder="0.00" required><label for="reason">Reason for adjustment</label><input id="reason" v-model="reason" minlength="5" maxlength="500" required><div class="status-note">Available: {{formatCredits(direction==='TRANSFER'?current.wallet.available:selected.wallet.available)}} · Reserved: {{formatCredits(selected.wallet.reserved)}}</div><footer><button class="primary">Review adjustment</button><button type="button" class="secondary" @click="dialog=false">Cancel</button></footer></form><template v-else><dl class="adjustment-review"><div><dt>Action</dt><dd>{{direction}}</dd></div><div><dt>Amount</dt><dd>{{formatCredits(units)}}</dd></div><div><dt>Target balance</dt><dd>{{formatCredits(selected.wallet.settled)}} → {{formatCredits(after)}}</dd></div><div><dt>Reason</dt><dd>{{reason}}</dd></div></dl><div class="status-note">This commits a real play-credit transaction. The server rechecks your authority, available balance and wallet version.</div><footer><button class="primary" :disabled="busy" @click="confirm">{{busy?'Saving…':'Confirm adjustment'}}</button><button class="secondary" :disabled="busy" @click="review=false">Back to edit</button></footer></template></section></div>
 <div v-if="createOpen" class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-label="Create account"><header><h2>Create account</h2><button class="icon-button" aria-label="Close create account" @click="createOpen=false"><Icon name="close"/></button></header><form @submit.prevent="create"><label for="parent">Reports to</label><select id="parent" v-model="parentId"><option v-for="member in members.filter(m=>m.role!=='PLAYER')" :key="member.id" :value="member.id">{{member.displayName}} · {{member.role}}</option></select><p>The new role is the next tier: Sub-distributor → Agent → Player. Starting balance: 0.00.</p><label for="new-name">Display name</label><input id="new-name" v-model="newName" required maxlength="100"><label for="new-user">Account ID</label><input id="new-user" v-model="newUsername" required pattern="[a-z0-9][a-z0-9._-]{2,63}" autocomplete="off"><label for="new-password">Initial password (12+ characters)</label><input id="new-password" v-model="newPassword" type="password" minlength="12" required autocomplete="new-password"><p v-if="error" class="error" role="alert">{{error}}</p><footer><button class="primary" :disabled="busy">Create zero-balance account</button></footer></form></section></div>
 <div v-if="manageOpen && selected" class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-label="Manage account access"><header><h2>{{selected.displayName}} · Access</h2><button class="icon-button" aria-label="Close account access" @click="manageOpen=false"><Icon name="close"/></button></header><p>Changing access revokes existing sessions. Credit balances and history stay intact.</p><label for="manage-reason">Reason</label><input id="manage-reason" v-model="manageReason" minlength="5" maxlength="500"><label for="reset-password">New password</label><input id="reset-password" v-model="resetPassword" type="password" autocomplete="new-password" minlength="12"><p v-if="error" class="error" role="alert">{{error}}</p><footer><button class="primary" :disabled="busy || resetPassword.length < 12 || manageReason.length < 5" @click="manage('RESET_PASSWORD')">Reset password</button><button class="secondary" :disabled="busy || manageReason.length < 5" @click="manage('SET_ACTIVE')">{{selected.active ? 'Suspend account' : 'Reactivate account'}}</button></footer></section></div><div v-if="verifyOpen" class="modal-backdrop verification"><section class="modal" role="dialog" aria-modal="true" aria-label="Verify administrator"><h2>Verify administrator</h2><p>Privileged changes require verification within the last five minutes.</p><form @submit.prevent="verify"><label for="verify-password">Password</label><input id="verify-password" v-model="verifyPassword" type="password" autocomplete="current-password" required><label for="verify-code">Authenticator code</label><input id="verify-code" v-model="verifyCode" inputmode="numeric" maxlength="6" autocomplete="one-time-code" required><p v-if="error" class="error" role="alert">{{error}}</p><footer><button class="primary" :disabled="busy">Verify</button><button type="button" class="secondary" @click="verifyOpen=false">Cancel</button></footer></form></section></div>
 </div>
</template>
