<script setup lang="ts">
import {computed,onMounted,ref,watch} from 'vue';
import {formatCredits as credits,parseCredits} from '@new-game/domain';
import Dialog from './Dialog.vue';
import {api,signIn,refreshAccount,clearSession,ApiError,type Account,type Member,type Entry,type Page,type Receipt} from './api';
type View='Dashboard'|'Players'|'Recharge records'|'Redeem records'|'Reward records'|'Game records'|'Adjustments'|'Organization'|'Sub-contractors'|'Agents'|'Audit log'|'Settings';
type Action='RECHARGE'|'REDEEM'|'ADD'|'REMOVE';
const current=ref<Account|null>(null),view=ref<View>('Dashboard'),busy=ref(false),error=ref(''),notice=ref(''),menu=ref(false);
const username=ref(''),password=ref('');
const members=ref<Page<Member>>({items:[],total:'0',page:1,pageSize:20}),records=ref<Page<Entry>>({items:[],total:'0',page:1,pageSize:20});
const query=ref(''),status=ref('ALL'),sort=ref('created'),order=ref('desc'),page=ref(1),pageSize=ref(20),from=ref(''),to=ref('');
const metrics=ref<Record<string,string>>({}),auditRows=ref<{id:string;event_type:string;actor:string;created_at:string}[]>([]);
const settings=ref<{account:{id:string;username:string;display_name:string;role:string;created_at:string};count:string;last_login:string;sessions:{created_at:string;expires_at:string;current:boolean}[]}|null>(null);
const receipt=ref<Receipt|null>(null),selected=ref<Member|null>(null),createOpen=ref(false),manageOpen=ref(false),creditOpen=ref(false),verifyOpen=ref(false);
const parentId=ref(''),newName=ref(''),newUsername=ref(''),newPassword=ref(''),confirmPassword=ref(''),createKey=ref('');
const editName=ref(''),resetPassword=ref(''),resetConfirm=ref(''),manageReason=ref(''),manageAction=ref<'EDIT_PROFILE'|'RESET_PASSWORD'|'SET_ACTIVE'|'SET_ARCHIVED'>('EDIT_PROFILE'),manageKey=ref('');
const verifyPassword=ref(''),ownPassword=ref(''),ownNewPassword=ref(''),ownConfirm=ref('');
const action=ref<Action>('RECHARGE'),amount=ref(''),reason=ref(''),review=ref(false),attempted=ref(false),request=ref<Record<string,string>|null>(null),committed=ref('');
const recordKinds:Partial<Record<View,string>>={'Recharge records':'RECHARGE','Redeem records':'REDEEM','Reward records':'REWARDS','Game records':'GAMES',Adjustments:'ADJUSTMENTS'};
const isAccounts=computed(()=>['Players','Organization','Sub-contractors','Agents'].includes(view.value));
const isRecords=computed(()=>Boolean(recordKinds[view.value]));
const nav=computed<View[]>(()=>['Dashboard','Players','Recharge records','Redeem records','Reward records','Game records',...(current.value?.role==='MAIN_ADMIN'?['Sub-contractors' as View]:[]),...(current.value?.role!=='AGENT'?['Agents' as View,'Organization' as View]:[]),...(current.value?.role==='MAIN_ADMIN'?['Adjustments' as View,'Audit log' as View]:[]),'Settings']);
const total=computed(()=>isAccounts.value?members.value.total:records.value.total);
const pages=computed(()=>Math.max(1,Math.ceil(Number(total.value)/pageSize.value)));
const role=(value:string)=>value==='SUB_DISTRIBUTOR'?'Sub-contractor':value.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const date=(value:string)=>value?new Date(value).toLocaleString(): '—';
const actionLabel=computed(()=>({RECHARGE:'Recharge account',REDEEM:'Redeem credits',ADD:'Issue credits',REMOVE:'Remove credits'})[action.value]);
const canCreate=computed(()=>current.value?.role!=='PLAYER');
const childLabel=computed(()=>current.value?.role==='MAIN_ADMIN'?'sub-contractor':current.value?.role==='SUB_DISTRIBUTOR'?'agent':'player');
const rank={MAIN_ADMIN:0,SUB_DISTRIBUTOR:1,AGENT:2,PLAYER:3};
function canTransfer(member:Member){return current.value&&member.active&&!member.archived&&member.branchEnabled&&rank[member.role]>rank[current.value.role];}
function clearPrivateState(){current.value=null;clearSession();members.value.items=[];records.value.items=[];settings.value=null;metrics.value={};auditRows.value=[];selected.value=null;receipt.value=null;createOpen.value=false;manageOpen.value=false;creditOpen.value=false;verifyOpen.value=false;password.value='';newPassword.value='';resetPassword.value='';ownPassword.value='';ownNewPassword.value='';verifyPassword.value='';confirmPassword.value='';resetConfirm.value='';ownConfirm.value='';}
async function run(work:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';try{await work();}catch(e){error.value=(e as Error).message;if(e instanceof ApiError){if(e.status===401)clearPrivateState();else if(e.code==='VERIFICATION_REQUIRED')verifyOpen.value=true;}}finally{busy.value=false;}}
function params(extra:Record<string,string>={}){return new URLSearchParams({page:String(page.value),pageSize:String(pageSize.value),search:query.value,...extra});}
async function loadPage(){
 if(view.value==='Dashboard')metrics.value=await api('operator/dashboard');
 else if(isAccounts.value)members.value=await api(`operator/accounts?${params({role:view.value==='Players'?'PLAYER':view.value==='Sub-contractors'?'SUB_DISTRIBUTOR':view.value==='Agents'?'AGENT':'ALL',status:status.value,sort:sort.value,order:order.value})}`);
 else if(isRecords.value)records.value=await api(`operator/records?${params({kind:recordKinds[view.value]!,...(from.value?{from:from.value}:{}),...(to.value?{to:to.value}:{})})}`);
 else if(view.value==='Settings')settings.value=await api('operator/settings');
 else if(view.value==='Audit log')auditRows.value=await api('admin/audit');
}
async function load(){const account=await refreshAccount();if(account.role==='PLAYER'){clearPrivateState();throw new Error('Use a staff account for the operator console.');}current.value=account;await loadPage();}
async function login(){await run(async()=>{await signIn(username.value,password.value);password.value='';await load();await restorePending();});}
async function logout(){await run(async()=>{await api('auth/logout',{});clearPrivateState();notice.value='';});}
function navigate(next:View){if(busy.value)return;view.value=next;menu.value=false;query.value='';page.value=1;status.value='ALL';from.value='';to.value='';notice.value='';void run(loadPage);}
function search(){page.value=1;void run(loadPage);}
function turnPage(delta:number){page.value+=delta;void run(loadPage);}
function resetFilters(){query.value='';status.value='ALL';sort.value='created';order.value='desc';from.value='';to.value='';search();}
function openCreate(parent?:Member){parentId.value=parent?.id||current.value!.id;newName.value='';newUsername.value='';newPassword.value='';confirmPassword.value='';createKey.value=crypto.randomUUID();error.value='';createOpen.value=true;}
async function create(){await run(async()=>{
 if(newPassword.value!==confirmPassword.value)throw new Error('Passwords do not match.');
 const result=await api<{id:string;username:string}>('admin/accounts',{parentId:parentId.value,username:newUsername.value,displayName:newName.value,password:newPassword.value,requestKey:createKey.value});
 createOpen.value=false;newPassword.value='';confirmPassword.value='';notice.value=`Created ${result.username} with 0.00 credits.`;await load();
});}
function openManage(member:Member){selected.value=member;editName.value=member.displayName;resetPassword.value='';resetConfirm.value='';manageReason.value='';manageAction.value='EDIT_PROFILE';manageKey.value=crypto.randomUUID();error.value='';manageOpen.value=true;}
async function manage(){await run(async()=>{
 const target=selected.value!;
 if(manageAction.value==='RESET_PASSWORD'&&resetPassword.value!==resetConfirm.value)throw new Error('Passwords do not match.');
 const details=manageAction.value==='EDIT_PROFILE'?{displayName:editName.value}:manageAction.value==='SET_ACTIVE'?{active:!target.active}:manageAction.value==='SET_ARCHIVED'?{archived:!target.archived}:{password:resetPassword.value};
 await api(`admin/accounts/${target.id}/manage`,{action:manageAction.value,reason:manageReason.value,requestKey:manageKey.value,...details});
 manageOpen.value=false;resetPassword.value='';resetConfirm.value='';notice.value='Account updated. '+(manageAction.value==='EDIT_PROFILE'?'':'Previous sessions were signed out.');await load();
});}
async function freshMember(id:string){const data=await api<Page<Member>>(`operator/accounts?${new URLSearchParams({search:id,role:'ALL'})}`);if(!data.items[0])throw new Error('This account is no longer available.');return data.items[0];}
function openCredit(member:Member,value:Action){void run(async()=>{if(sessionStorage.getItem(pendingKey())){await restorePending();if(creditOpen.value)return;}selected.value=await freshMember(member.id);current.value=await refreshAccount();action.value=value;amount.value='';reason.value='';request.value=null;review.value=false;attempted.value=false;committed.value='';creditOpen.value=true;});}
function preview(){error.value='';try{
 const target=selected.value!,staff=current.value!,units=parseCredits(amount.value);
 if(reason.value.trim().length<5)throw new Error('Add a reason of at least 5 characters.');
 const source=action.value==='RECHARGE'?staff.wallet:target.wallet;
 if(action.value!=='ADD'&&BigInt(units)>BigInt(source.available))throw new Error('The amount exceeds available credits. Reserved credits cannot be moved.');
 request.value={targetId:target.id,amount:units,reason:reason.value.trim(),requestKey:crypto.randomUUID(),expectedVersion:['RECHARGE','REDEEM'].includes(action.value)?staff.wallet.version:target.wallet.version,...(['RECHARGE','REDEEM'].includes(action.value)?{targetVersion:target.wallet.version}:{direction:action.value})};review.value=true;
 }catch(e){error.value=(e as Error).message;}}
const targetAfter=computed(()=>selected.value&&request.value?(BigInt(selected.value.wallet.settled)+(['REDEEM','REMOVE'].includes(action.value)?-1n:1n)*BigInt(request.value.amount)).toString():'0');
const staffAfter=computed(()=>current.value&&request.value?(BigInt(current.value.wallet.settled)+(action.value==='REDEEM'?1n:-1n)*BigInt(request.value.amount)).toString():'0');
watch([newName,newUsername,newPassword,parentId],()=>{createKey.value=crypto.randomUUID();});
watch([manageAction,editName,resetPassword,manageReason],()=>{manageKey.value=crypto.randomUUID();});
const pendingKey=()=>`ng.operator.pending-transfer.v1:${current.value!.id}`;
function savePending(){try{sessionStorage.setItem(pendingKey(),JSON.stringify({actorId:current.value!.id,action:action.value,request:request.value}));}catch{throw new Error('Session storage is required to safely recover a credit request.');}}
function clearPending(){sessionStorage.removeItem(pendingKey());}
async function restorePending(){
 const raw=sessionStorage.getItem(pendingKey());if(!raw||!current.value)return;
 try{const stored=JSON.parse(raw);if(stored.actorId!==current.value.id)return;if(!['RECHARGE','REDEEM','ADD','REMOVE'].includes(stored.action)||!stored.request?.targetId)return;
 selected.value=await freshMember(stored.request.targetId);request.value=stored.request;action.value=stored.action;amount.value=credits(stored.request.amount).replaceAll(',','');reason.value=stored.request.reason;review.value=true;attempted.value=true;committed.value='';creditOpen.value=true;notice.value='An unfinished credit request was restored. Check its result using the same request ID.';
 }catch{error.value='A pending request could not be restored. Review transaction records before starting another transfer.';}
}
async function commit(){await run(async()=>{
 savePending();attempted.value=true;
 try{const result=await api<{id:string}>(action.value==='RECHARGE'?'credit-transfers':action.value==='REDEEM'?'operator/redeems':'admin/credit-adjustments',request.value);committed.value=result.id;clearPending();await load();selected.value=await freshMember(selected.value!.id);}
 catch(e){if(e instanceof ApiError&&e.status>=400&&e.status<500&&e.code!=='VERIFICATION_REQUIRED'&&e.status!==401){clearPending();request.value=null;review.value=false;attempted.value=false;selected.value=await freshMember(selected.value!.id);current.value=await refreshAccount();}throw e;}
});}
async function showReceipt(id:string){await run(async()=>{receipt.value=await api(`operator/receipts/${id}`);});}
async function verify(){await run(async()=>{await api('auth/verify',{password:verifyPassword.value});verifyPassword.value='';verifyOpen.value=false;notice.value='Verified. You can confirm your action.';});}
async function changeOwnPassword(){await run(async()=>{if(ownNewPassword.value!==ownConfirm.value)throw new Error('Passwords do not match.');await api('auth/password',{currentPassword:ownPassword.value,newPassword:ownNewPassword.value});clearPrivateState();ownConfirm.value='';notice.value='Password changed. Sign in with your new password.';});}
function printReceipt(){window.print();}
onMounted(async()=>{try{await load();await restorePending();}catch(e){if(!(e instanceof ApiError&&e.status===401))error.value=(e as Error).message;}});
</script>
<template>
 <main v-if="!current" class="login-page"><section class="login-card"><div class="brand-mark">N</div><p class="eyebrow">NEW GAME · OPERATOR CONSOLE</p><h1>Welcome back</h1><p class="muted">Manage your players and play credits.</p><p v-if="notice" class="success" role="status">{{notice}}</p><form @submit.prevent="login"><label>Staff ID<input v-model="username" autocomplete="username" required></label><label>Password<input v-model="password" type="password" autocomplete="current-password" required></label><p v-if="error" class="error" role="alert">{{error}}</p><button class="primary wide" :disabled="busy">{{busy?'Signing in…':'Sign in'}}</button></form></section></main>
 <div v-else class="shell">
  <aside class="sidebar" :class="{expanded:menu}"><a class="brand" href="#" @click.prevent="navigate('Dashboard')"><span class="brand-mark">N</span><span>NEW GAME<small>Operator console</small></span></a><p class="nav-label">MANAGEMENT</p><nav aria-label="Console sections"><button v-for="item in nav" :key="item" :class="{active:view===item}" :aria-current="view===item?'page':undefined" :disabled="busy" @click="navigate(item)"><span class="nav-dot"/>{{item}}</button></nav><div class="sidebar-foot"><span class="live-dot"/>Account management</div></aside>
  <div class="workspace"><header class="topbar"><button class="menu-toggle" aria-label="Toggle navigation" :aria-expanded="menu" @click="menu=!menu">☰</button><div class="wallet-top"><small>Your available credits</small><strong>{{credits(current.wallet.available)}}</strong></div><div class="staff-top"><span>{{current.displayName}}<small>{{role(current.role)}}</small></span><button :disabled="busy" @click="logout">Sign out</button></div></header>
   <main class="content" :aria-busy="busy"><div class="page-heading"><div><p class="eyebrow">WORKSPACE / {{view.toUpperCase()}}</p><h1>{{view}}</h1><p class="muted">{{view==='Dashboard'?'An overview of your players and credit activity.':view==='Players'?'Create accounts, manage access and move play credits.':view==='Settings'?'Your account and sign-in security.':view==='Organization'?'Accounts in your authorized branch.':isRecords?'Committed ledger records · Date filters use UTC.':'Account changes and operator actions.'}}</p></div><div class="actions"><button :disabled="busy" @click="run(load)">↻ Refresh</button><button v-if="canCreate&&isAccounts" class="primary" :disabled="busy" @click="openCreate()">+ Create {{childLabel}}</button></div></div>
   <p v-if="error&&!creditOpen&&!createOpen&&!manageOpen&&!verifyOpen" class="error" role="alert">{{error}}</p><p v-if="notice" class="success" role="status">{{notice}}</p>
   <template v-if="view==='Dashboard'"><div class="metric-grid"><article class="metric feature"><span class="metric-symbol">♙</span><small>Registered players</small><strong>{{metrics.players||'0'}}</strong><p>{{metrics.enabled_players||'0'}} enabled accounts</p></article><article class="metric"><span class="metric-symbol blue">↗</span><small>Active in the last 24 hours</small><strong>{{metrics.active_24h||'0'}}</strong><p>Players who signed in</p></article><article class="metric"><span class="metric-symbol violet">+</span><small>New players yesterday</small><strong>{{metrics.new_yesterday||'0'}}</strong><p>UTC calendar day</p></article><article class="metric"><span class="metric-symbol green">◈</span><small>Player available credits</small><strong>{{credits(metrics.player_available||'0')}}</strong><p>Total across your branch</p></article></div>
    <div class="dashboard-columns"><section class="panel"><div class="panel-heading"><h2>Yesterday’s activity</h2><span class="badge">UTC</span></div><div class="summary-row"><span>Players recharged</span><b>{{metrics.recharged_yesterday||'0'}}</b></div><div class="summary-row"><span>Players redeemed</span><b>{{metrics.redeemed_yesterday||'0'}}</b></div><div class="summary-row"><span>Recharge credits</span><b class="positive">+{{credits(metrics.recharge_yesterday||'0')}}</b></div><div class="summary-row"><span>Redeemed credits</span><b>{{credits(metrics.redeem_yesterday||'0')}}</b></div></section><section class="panel"><div class="panel-heading"><h2>Credit movement</h2><span class="badge">ALL TIME</span></div><div class="movement-total"><small>Recharged to players</small><strong>{{credits(metrics.recharge_total||'0')}}</strong></div><div class="movement-total"><small>Redeemed from players</small><strong>{{credits(metrics.redeem_total||'0')}}</strong></div><p class="fine">Transfers of existing credits. Manual issuance and game winnings appear in their own records.</p></section></div><section class="panel quick-start"><div><h2>Ready to manage your players?</h2><p class="muted">Find an account to recharge, redeem or update access.</p></div><button class="primary" @click="navigate('Players')">Open player management →</button></section><p class="fine">Updated {{date(metrics.asOf)}}</p>
   </template>
   <section v-else-if="isAccounts||isRecords" class="panel data-panel"><form class="filters" @submit.prevent="search"><label class="search-field">Search<input v-model="query" :placeholder="isAccounts?'Account, display name or full ID':'Account or receipt ID'"></label><template v-if="isAccounts"><label>Status<select v-model="status"><option value="ALL">All statuses</option><option value="ACTIVE">Active</option><option value="SUSPENDED">Suspended</option><option value="ARCHIVED">Archived</option></select></label><label>Sort by<select v-model="sort"><option value="created">Registration date</option><option value="username">Account ID</option><option value="balance">Available credits</option></select></label><label>Order<select v-model="order"><option value="desc">Descending</option><option value="asc">Ascending</option></select></label></template><template v-else><label>From (UTC)<input v-model="from" type="date"></label><label>To (UTC)<input v-model="to" type="date" :min="from"></label></template><button class="primary" :disabled="busy">Search</button><button type="button" :disabled="busy" @click="resetFilters">Reset</button></form>
    <div class="table-caption"><strong>{{total}} {{isAccounts?'accounts':'records'}}</strong><span v-if="isAccounts">Only available credits can be moved.</span><span v-else-if="view==='Game records'">Stakes and winnings · Separate entries per committed round</span></div>
    <div class="table-scroll"><table v-if="isAccounts"><thead><tr><th>Account</th><th>Status</th><th class="number">Available</th><th class="number">Reserved</th><th>Branch / Role</th><th>Registered</th><th>Actions</th></tr></thead><tbody><tr v-for="member in members.items" :key="member.id"><td><strong>{{member.displayName}}</strong><span class="cell-sub">{{member.username}}</span><small class="account-id" :title="member.id">{{member.id.slice(0,8)}}</small></td><td><span class="status" :class="{suspended:!member.active||member.archived||!member.branchEnabled}">{{member.archived?'Archived':!member.active?'Suspended':!member.branchEnabled?'Branch blocked':'Active'}}</span></td><td class="number balance">{{credits(member.wallet.available)}}</td><td class="number muted">{{credits(member.wallet.reserved)}}</td><td>{{member.branch}}<span class="cell-sub">{{role(member.role)}}</span></td><td class="date-cell">{{date(member.createdAt)}}</td><td><div class="row-actions"><button v-if="canTransfer(member)" class="link" :disabled="busy" @click="openCredit(member,'RECHARGE')">Recharge</button><button v-if="member.canRedeem" class="link" :disabled="busy" @click="openCredit(member,'REDEEM')">Redeem</button><button v-if="member.canManage" class="link" :disabled="busy" @click="openManage(member)">Edit / Access</button><template v-if="current.role==='MAIN_ADMIN'"><button class="link" :disabled="busy" @click="openCredit(member,'ADD')">Add credits</button><button class="link" :disabled="busy" @click="openCredit(member,'REMOVE')">Remove credits</button><button v-if="member.role!=='PLAYER'&&member.active&&!member.archived&&member.branchEnabled" class="link" @click="openCreate(member)">Create child</button></template></div></td></tr><tr v-if="!members.items.length"><td colspan="7" class="empty"><h3>No accounts found</h3><p>Try a different search or create a player.</p></td></tr></tbody></table>
    <table v-else><thead><tr><th>Receipt</th><th>Account</th><th>Type</th><th class="number">Before</th><th class="number">Change</th><th class="number">After</th><th>Operator</th><th>Date</th></tr></thead><tbody><tr v-for="entry in records.items" :key="entry.id"><td><button class="link mono" :disabled="busy" @click="showReceipt(entry.id)">{{entry.id.slice(0,8)}} ↗</button></td><td><strong>{{entry.display_name}}</strong><span class="cell-sub">{{entry.username}}</span></td><td><span class="badge">{{role(entry.kind)}}</span><span v-if="entry.game_id" class="cell-sub">{{entry.game_id}}</span></td><td class="number">{{credits(entry.before_units)}}</td><td class="number" :class="{positive:BigInt(entry.units)>0n}">{{BigInt(entry.units)>0n?'+':''}}{{credits(entry.units)}}</td><td class="number balance">{{credits(entry.after_units)}}</td><td>{{entry.actor}}</td><td class="date-cell">{{date(entry.created_at)}}</td></tr><tr v-if="!records.items.length"><td colspan="8" class="empty"><h3>No records found</h3><p>No committed activity matches these filters.</p></td></tr></tbody></table></div>
    <footer class="pagination"><label>Rows<select v-model="pageSize" :disabled="busy" @change="search"><option :value="10">10</option><option :value="20">20</option><option :value="50">50</option><option :value="100">100</option></select></label><span>Page {{page}} of {{pages}}</span><button :disabled="busy||page<=1" @click="turnPage(-1)">Previous</button><button :disabled="busy||page>=pages" @click="turnPage(1)">Next</button></footer>
   </section>
   <section v-else-if="view==='Audit log'" class="panel data-panel"><div class="panel-heading"><h2>Latest 100 audit events</h2><span class="badge">IMMUTABLE</span></div><div class="table-scroll"><table><thead><tr><th>Event</th><th>Actor</th><th>Date</th><th>Reference</th></tr></thead><tbody><tr v-for="event in auditRows" :key="event.id"><td>{{role(event.event_type)}}</td><td>{{event.actor}}</td><td>{{date(event.created_at)}}</td><td class="mono">{{event.id}}</td></tr></tbody></table></div></section>
   <div v-else-if="view==='Settings'&&settings" class="settings-grid"><section class="panel"><div class="panel-heading"><h2>Account information</h2></div><dl class="details"><div><dt>Display name</dt><dd>{{settings.account.display_name}}</dd></div><div><dt>Staff ID</dt><dd>{{settings.account.username}}</dd></div><div><dt>Role</dt><dd>{{role(settings.account.role)}}</dd></div><div><dt>Account reference</dt><dd class="mono">{{settings.account.id}}</dd></div><div><dt>Sign-ins</dt><dd>{{settings.count}}</dd></div><div><dt>Last sign-in</dt><dd>{{date(settings.last_login)}}</dd></div></dl><h3>Active sessions</h3><article v-for="(item,i) in settings.sessions" :key="i" class="session-row"><span>{{item.current?'This session':'Signed-in session'}}<small>{{date(item.created_at)}}</small></span><span class="badge">Expires {{date(item.expires_at)}}</span></article></section><section class="panel"><div class="panel-heading"><h2>Change password</h2></div><p class="muted">Use at least 12 characters. Changing your password signs out all sessions.</p><form @submit.prevent="changeOwnPassword"><label>Current password<input v-model="ownPassword" type="password" autocomplete="current-password" required></label><label>New password<input v-model="ownNewPassword" type="password" autocomplete="new-password" minlength="12" maxlength="256" required></label><label>Confirm new password<input v-model="ownConfirm" type="password" autocomplete="new-password" minlength="12" required></label><button class="primary" :disabled="busy">Change password and sign out</button></form></section></div>
   <footer class="site-footer"><span>New Game · Operator console</span></footer></main></div>
  <Dialog v-if="createOpen" title="Create account" :busy="busy" @close="createOpen=false"><form @submit.prevent="create"><p class="note">Every new account starts with <b>0.00 credits</b>.</p><label v-if="current.role==='MAIN_ADMIN'">Parent account ID<input v-model="parentId" required><small>The next role is selected from the parent: Main Admin → Sub-contractor → Agent → Player. Use “Create child” in Organization to select a parent.</small></label><p v-else class="muted">New {{childLabel}} will belong to {{current.displayName}}.</p><label>Display name<input v-model="newName" maxlength="100" required></label><label>Login ID<input v-model="newUsername" pattern="[a-z0-9][a-z0-9._-]{2,63}" autocomplete="off" required><small>3–64 lowercase letters, numbers, dots, hyphens or underscores.</small></label><label>Initial password<input v-model="newPassword" type="password" autocomplete="new-password" minlength="12" maxlength="256" required></label><label>Confirm password<input v-model="confirmPassword" type="password" autocomplete="new-password" required></label><p v-if="error" class="error" role="alert">{{error}}</p><footer><button type="button" :disabled="busy" @click="createOpen=false">Cancel</button><button class="primary" :disabled="busy">Create account</button></footer></form></Dialog>
  <Dialog v-if="manageOpen&&selected" :title="`Manage ${selected.username}`" :busy="busy" @close="manageOpen=false"><form @submit.prevent="manage"><label>Action<select v-model="manageAction"><option value="EDIT_PROFILE">Edit display name</option><option value="RESET_PASSWORD">Reset password</option><option v-if="!selected.archived" value="SET_ACTIVE">{{selected.active?'Suspend account':'Reactivate account'}}</option><option value="SET_ARCHIVED">{{selected.archived?'Restore archived account':'Remove / archive account'}}</option></select></label><label v-if="manageAction==='EDIT_PROFILE'">Display name<input v-model="editName" maxlength="100" required></label><template v-if="manageAction==='RESET_PASSWORD'"><label>New password<input v-model="resetPassword" type="password" autocomplete="new-password" minlength="12" maxlength="256" required></label><label>Confirm password<input v-model="resetConfirm" type="password" autocomplete="new-password" required></label></template><p v-if="manageAction!=='EDIT_PROFILE'" class="note">This signs the account out. Suspending or archiving staff also blocks their branch. Balances and transaction history are preserved; restoring staff does not reactivate individually suspended accounts.</p><label>Reason<input v-model="manageReason" minlength="5" maxlength="500" required></label><p v-if="error" class="error" role="alert">{{error}}</p><footer><button type="button" :disabled="busy" @click="manageOpen=false">Cancel</button><button class="primary" :disabled="busy">Confirm change</button></footer></form></Dialog>
  <Dialog v-if="creditOpen&&selected" :title="actionLabel" :busy="busy" @close="creditOpen=false"><div class="target-card"><span class="avatar">{{selected.displayName.slice(0,2).toUpperCase()}}</span><span><strong>{{selected.displayName}}</strong><small>{{selected.username}}</small></span><span class="target-balance"><small>Available</small><strong>{{credits(selected.wallet.available)}}</strong></span></div><p v-if="error" class="error" role="alert">{{error}}</p><template v-if="committed"><p class="success" role="status">Transfer committed successfully.</p><p class="mono wrap">Receipt {{committed}}</p><footer><button @click="showReceipt(committed)">View receipt</button><button class="primary" @click="creditOpen=false">Done</button></footer></template><form v-else-if="!review" @submit.prevent="preview"><label>Amount in play credits<input v-model="amount" inputmode="decimal" placeholder="0.00" required></label><label>Reason<input v-model="reason" minlength="5" maxlength="500" required></label><p class="note">{{action==='RECHARGE'?`Your available credits: ${credits(current.wallet.available)}.`:`Account reserved credits: ${credits(selected.wallet.reserved)}.`}} {{action==='REDEEM'?'Available credits move back to your wallet.':''}}</p><footer><button type="button" @click="creditOpen=false">Cancel</button><button class="primary">Review transfer</button></footer></form><template v-else-if="request"><p v-if="attempted" class="note">Check this request’s result using the same ID. Retrying cannot duplicate a committed transfer.</p><dl class="details"><div><dt>Account</dt><dd>{{selected.username}}</dd></div><div><dt>Amount</dt><dd><b>{{credits(request.amount)}}</b></dd></div><template v-if="!attempted"><div><dt>Account balance</dt><dd>{{credits(selected.wallet.settled)}} → {{credits(targetAfter)}}</dd></div><div v-if="action==='RECHARGE'||action==='REDEEM'"><dt>Your balance</dt><dd>{{credits(current.wallet.settled)}} → {{credits(staffAfter)}}</dd></div></template><div><dt>Reason</dt><dd>{{request.reason}}</dd></div><div><dt>Request ID</dt><dd class="mono wrap">{{request.requestKey}}</dd></div></dl><footer><button v-if="!attempted" :disabled="busy" @click="review=false">Back</button><button class="primary" :disabled="busy" @click="commit">{{busy?'Processing…':attempted?'Check / retry request':'Confirm transfer'}}</button></footer></template></Dialog>
  <Dialog v-if="verifyOpen" title="Verify your session" :busy="busy" @close="verifyOpen=false"><p class="muted">Sensitive actions require a recent verification.</p><form @submit.prevent="verify"><label>Password<input v-model="verifyPassword" type="password" autocomplete="current-password" required></label><p v-if="error" class="error" role="alert">{{error}}</p><footer><button class="primary" :disabled="busy">Verify session</button></footer></form></Dialog>
  <Dialog v-if="receipt" title="Transaction receipt" :busy="busy" @close="receipt=null"><section class="receipt"><p class="eyebrow">NEW GAME · {{role(receipt.kind)}}</p><h3>{{receipt.username}}</h3><strong class="receipt-amount">{{credits(receipt.units)}} play credits</strong><dl class="details"><div><dt>Receipt ID</dt><dd class="mono wrap">{{receipt.id}}</dd></div><div><dt>Request ID</dt><dd class="mono wrap">{{receipt.request_id}}</dd></div><div><dt>Operator</dt><dd>{{receipt.actor}}</dd></div><div><dt>Date</dt><dd>{{date(receipt.created_at)}}</dd></div><div><dt>Reason</dt><dd>{{receipt.reason}}</dd></div><div><dt>Before → After</dt><dd>{{credits(receipt.before_units)}} → {{credits(receipt.after_units)}}</dd></div><div><dt>Wallet version</dt><dd>{{receipt.wallet_version}}</dd></div></dl><template v-if="receipt.round_id"><h3>Committed game round</h3><dl class="details"><div><dt>Game</dt><dd>{{receipt.game_id}}</dd></div><div><dt>Round ID</dt><dd class="mono wrap">{{receipt.round_id}}</dd></div><div><dt>Stake / Award</dt><dd>{{credits(receipt.stake_units!)}} / {{credits(receipt.award_units!)}}</dd></div><div><dt>Rules version</dt><dd>{{receipt.profile_id}}</dd></div></dl></template><h3>Visible wallet entries</h3><div v-for="posting in receipt.postings" :key="posting.username" class="summary-row"><span>{{posting.username}}</span><b>{{credits(posting.units)}}</b></div></section><footer class="no-print"><button @click="receipt=null">Close</button><button class="primary" @click="printReceipt">Print receipt</button></footer></Dialog>
 </div>
</template>
