<script setup lang="ts">
import {computed,onMounted,ref,watch} from 'vue';
import {formatCredits as credits,parseCredits} from '@new-game/domain';
import Dialog from './Dialog.vue';
import DevicePanel from './DevicePanel.vue';
import ApiPanel from './ApiPanel.vue';
import {api,signIn,refreshAccount,clearSession,ApiError,type Account,type Member,type Entry,type Page,type Receipt} from './api';
type View='Home'|'Total Account'|'Agent Rewards'|'User Management'|'Recharge Record'|'Redeem Record'|'Reward Record'|'Game Records'|'Sub-contractors'|'Agents'|'Wager Bonus FAQ'|'Setting'|'API Download'|'Login Device';
type Action='RECHARGE'|'REDEEM'|'ADD'|'REMOVE';
const current=ref<Account|null>(null),view=ref<View>('Home'),busy=ref(false),error=ref(''),notice=ref(''),menu=ref(window.innerWidth<=600);
const username=ref(''),password=ref('');
const members=ref<Page<Member>>({items:[],total:'0',page:1,pageSize:20}),records=ref<Page<Entry>>({items:[],total:'0',page:1,pageSize:20});
const query=ref(''),status=ref('ALL'),sort=ref('created'),order=ref('desc'),page=ref(1),pageSize=ref(20),from=ref(''),to=ref('');
const metrics=ref<Record<string,string>>({});
const settings=ref<{account:{id:string;public_id:string;username:string;display_name:string;role:string;created_at:string};count:string;last_login:string;lastIp:string|null;sessions:{created_at:string;expires_at:string;current:boolean}[]}|null>(null);
const receipt=ref<Receipt|null>(null),selected=ref<Member|null>(null),createOpen=ref(false),manageOpen=ref(false),creditOpen=ref(false),verifyOpen=ref(false);
const parentId=ref(''),newName=ref(''),newUsername=ref(''),newPassword=ref(''),confirmPassword=ref(''),createKey=ref('');
const editName=ref(''),resetPassword=ref(''),resetConfirm=ref(''),manageReason=ref(''),manageAction=ref<'EDIT_PROFILE'|'RESET_PASSWORD'|'SET_ACTIVE'|'SET_ARCHIVED'>('EDIT_PROFILE'),manageKey=ref('');
const verifyPassword=ref(''),ownPassword=ref(''),ownNewPassword=ref(''),ownConfirm=ref('');
const action=ref<Action>('RECHARGE'),amount=ref(''),reason=ref(''),review=ref(false),attempted=ref(false),request=ref<Record<string,string>|null>(null),committed=ref('');
const recordKinds:Partial<Record<View,string>>={'Recharge Record':'RECHARGE','Redeem Record':'REDEEM','Reward Record':'REWARDS'};
const isAccounts=computed(()=>['User Management','Sub-contractors','Agents'].includes(view.value));
const isRecords=computed(()=>Boolean(recordKinds[view.value]));
const groups=computed(()=>[
 {title:'Admin Management',items:['Home','Total Account','Agent Rewards',...(current.value?.role==='MAIN_ADMIN'?['Sub-contractors']:[]),...(current.value?.role!=='AGENT'?['Agents']:[])] as View[]},
 {title:'Game User',items:['User Management','Redeem Record','Recharge Record','Reward Record','Game Records','Wager Bonus FAQ'] as View[]},
 {title:'Setting',items:['Setting','API Download','Login Device'] as View[]}
]);
const expanded=ref('Admin Management'),editor=ref(''),bonusTab=ref('Rewards'),includeSub=ref('Yes'),searchField=ref('Account'),gotoPage=ref(1);
type Round={id:string;public_id:string;username:string;game_id:string;before_units:string;after_units:string;stake_units:string;award_units:string;created_at:string;manager:string|null};
type AgentTotal={id:string;username:string;role:string;played:string;won:string;recharged:string;redeemed:string};
const rounds=ref<Page<Round>&{played:string;won:string}>({items:[],total:'0',page:1,pageSize:20,played:'0',won:'0'});
const totals=ref<Page<AgentTotal>&{played:string;won:string;recharged:string;redeemed:string}>({items:[],total:'0',page:1,pageSize:20,played:'0',won:'0',recharged:'0',redeemed:'0'});
const total=computed(()=>isAccounts.value?members.value.total:view.value==='Game Records'?rounds.value.total:view.value==='Total Account'?totals.value.total:records.value.total);
const net=(a:string|undefined,b:string|undefined)=>credits((BigInt(a||'0')-BigInt(b||'0')).toString());
const gameTitle=(value:string)=>value.split('-').map(s=>s[0].toUpperCase()+s.slice(1)).join(' ');
const homeCards=computed(()=>[
 ['Total Number Of Players Registered',metrics.value.players],['Number Of People Recharged Yesterday',metrics.value.recharged_yesterday],['Number Of Withdrawals Yesterday',metrics.value.redeemed_yesterday],['Active Population',metrics.value.active_24h],['Number Of New Registrations Yesterday',metrics.value.new_yesterday],
 ['Recharge Amount Yesterday',credits(metrics.value.recharge_yesterday||'0')],['Amount Withdrawn Yesterday',credits(metrics.value.redeem_yesterday||'0')],['Income Yesterday',net(metrics.value.recharge_yesterday,metrics.value.redeem_yesterday)],['Accumulated Recharge Amount',credits(metrics.value.recharge_total||'0')],['Accumulated Withdrawal',credits(metrics.value.redeem_total||'0')]
]);
const parentChoices=ref<Member[]>([]);
const pages=computed(()=>Math.max(1,Math.ceil(Number(total.value)/pageSize.value)));
const role=(value:string)=>value==='SUB_DISTRIBUTOR'?'Sub-contractor':value.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const date=(value:string)=>value?new Date(value).toLocaleString(): '—';
const actionLabel=computed(()=>({RECHARGE:'Recharge account',REDEEM:'Redeem credits',ADD:'Issue credits',REMOVE:'Remove credits'})[action.value]);
const canCreate=computed(()=>current.value?.role!=='PLAYER');
const childLabel=computed(()=>current.value?.role==='MAIN_ADMIN'?'sub-contractor':current.value?.role==='SUB_DISTRIBUTOR'?'agent':'player');
const rank={MAIN_ADMIN:0,SUB_DISTRIBUTOR:1,AGENT:2,PLAYER:3};
function canTransfer(member:Member){return current.value&&member.active&&!member.archived&&member.branchEnabled&&rank[member.role]>rank[current.value.role];}
function clearPrivateState(){current.value=null;clearSession();members.value.items=[];records.value.items=[];settings.value=null;metrics.value={};rounds.value.items=[];totals.value.items=[];selected.value=null;receipt.value=null;createOpen.value=false;manageOpen.value=false;creditOpen.value=false;verifyOpen.value=false;password.value='';newPassword.value='';resetPassword.value='';ownPassword.value='';ownNewPassword.value='';verifyPassword.value='';confirmPassword.value='';resetConfirm.value='';ownConfirm.value='';}
async function run(work:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';try{await work();}catch(e){error.value=(e as Error).message;if(e instanceof ApiError){if(e.status===401)clearPrivateState();else if(e.code==='VERIFICATION_REQUIRED')verifyOpen.value=true;}}finally{busy.value=false;}}
function params(extra:Record<string,string>={}){return new URLSearchParams({page:String(page.value),pageSize:String(pageSize.value),search:query.value,...extra});}
async function loadPage(){
 if(view.value==='Home'){metrics.value=await api('operator/dashboard');settings.value=await api('operator/settings');}
 else if(isAccounts.value)members.value=await api(`operator/accounts?${params({role:view.value==='User Management'?'PLAYER':view.value==='Sub-contractors'?'SUB_DISTRIBUTOR':view.value==='Agents'?'AGENT':'ALL',status:status.value,sort:sort.value,order:order.value})}`);
 else if(isRecords.value)records.value=await api(`operator/records?${params({kind:recordKinds[view.value]!,...(from.value?{from:from.value}:{}),...(to.value?{to:to.value}:{})})}`);
 else if(view.value==='Setting')settings.value=await api('operator/settings');
 else if(view.value==='Game Records')rounds.value=await api(`operator/rounds?${params({...(from.value?{from:from.value}:{}),...(to.value?{to:to.value}:{})})}`);
 else if(view.value==='Total Account')totals.value=await api(`operator/totals?${params({...(from.value?{from:from.value}:{}),...(to.value?{to:to.value}:{})})}`);
}
async function load(){const account=await refreshAccount();if(account.role==='PLAYER'){clearPrivateState();throw new Error('Use a staff account for the operator console.');}current.value=account;await loadPage();}
async function login(){await run(async()=>{await signIn(username.value,password.value);view.value='Home';expanded.value='Admin Management';password.value='';await load();await restorePending();});}
async function logout(){await run(async()=>{await api('auth/logout',{});clearPrivateState();notice.value='';});}
function navigate(next:View){if(busy.value)return;view.value=next;if(window.innerWidth<=600)menu.value=true;query.value='';page.value=1;status.value='ALL';from.value='';to.value='';notice.value='';editor.value='';gotoPage.value=1;void run(loadPage);}
function search(){page.value=1;void run(loadPage);}
function turnPage(delta:number){page.value=Math.min(pages.value,Math.max(1,page.value+delta));gotoPage.value=page.value;void run(loadPage);}
function resetFilters(){query.value='';status.value='ALL';sort.value='created';order.value='desc';from.value='';to.value='';search();}
function openCreate(parent?:Member){void run(async()=>{
 parentId.value=parent?.id||current.value!.id;parentChoices.value=[];
 if(current.value!.role==='MAIN_ADMIN'&&!parent&&view.value!=='Sub-contractors'){
  const desired=view.value==='Agents'?'SUB_DISTRIBUTOR':'AGENT';
  let next=1;do{const batch=await api<Page<Member>>(`operator/accounts?role=${desired}&status=ACTIVE&pageSize=100&page=${next}`);parentChoices.value.push(...batch.items.filter(m=>m.branchEnabled));if(next*100>=Number(batch.total))break;next++;}while(next<=100);
  parentId.value=parentChoices.value[0]?.id||'';
 }
 newName.value='';newUsername.value='';newPassword.value='';confirmPassword.value='';createKey.value=crypto.randomUUID();error.value='';createOpen.value=true;
});}
async function create(){await run(async()=>{
 if(newPassword.value!==confirmPassword.value)throw new Error('Passwords do not match.');
 const result=await api<{id:string;username:string}>('admin/accounts',{parentId:parentId.value,username:newUsername.value,displayName:newName.value,password:newPassword.value,requestKey:createKey.value});
 createOpen.value=false;newPassword.value='';confirmPassword.value='';notice.value=`Created ${result.username} with 0.00 credits.`;await load();
});}
function openManage(member:Member,action:'EDIT_PROFILE'|'RESET_PASSWORD'|'SET_ACTIVE'|'SET_ARCHIVED'='EDIT_PROFILE'){selected.value=member;editName.value=member.displayName;resetPassword.value='';resetConfirm.value='';manageReason.value='';manageAction.value=action;editor.value='';manageKey.value=crypto.randomUUID();error.value='';manageOpen.value=true;}
async function manage(){await run(async()=>{
 const target=selected.value!;
 if(manageAction.value==='RESET_PASSWORD'&&resetPassword.value!==resetConfirm.value)throw new Error('Passwords do not match.');
 const details=manageAction.value==='EDIT_PROFILE'?{displayName:editName.value}:manageAction.value==='SET_ACTIVE'?{active:!target.active}:manageAction.value==='SET_ARCHIVED'?{archived:!target.archived}:{password:resetPassword.value};
 await api(`admin/accounts/${target.id}/manage`,{action:manageAction.value,reason:manageReason.value,requestKey:manageKey.value,...details});
 manageOpen.value=false;resetPassword.value='';resetConfirm.value='';notice.value='Account updated. '+(manageAction.value==='EDIT_PROFILE'?'':'Previous sessions were signed out.');await load();
});}
async function freshMember(id:string){const data=await api<Page<Member>>(`operator/accounts?${new URLSearchParams({search:id,role:'ALL'})}`);if(!data.items[0])throw new Error('This account is no longer available.');return data.items[0];}
function openCredit(member:Member,value:Action){void run(async()=>{if(sessionStorage.getItem(pendingKey())){await restorePending();if(creditOpen.value)return;}selected.value=await freshMember(member.id);current.value=await refreshAccount();action.value=value;amount.value='';reason.value='';request.value=null;review.value=false;attempted.value=false;committed.value='';creditOpen.value=true;});}
function preview(){error.value='';try{
 const target=selected.value!,staff=current.value!,units=parseCredits(amount.value);
 if(reason.value.trim().length<5)throw new Error('Add a reason of at least 5 characters.');
 const source=action.value==='RECHARGE'?staff.wallet:target.wallet;
 if(action.value!=='ADD'&&BigInt(units)>BigInt(source.available))throw new Error('The amount exceeds available credits. Reserved credits cannot be moved.');
 request.value={targetId:target.id,amount:units,reason:reason.value.trim(),requestKey:crypto.randomUUID(),expectedVersion:['RECHARGE','REDEEM'].includes(action.value)?staff.wallet.version:target.wallet.version,...(['RECHARGE','REDEEM'].includes(action.value)?{targetVersion:target.wallet.version}:{direction:action.value})};review.value=true;
 }catch(e){error.value=(e as Error).message;}}
const targetAfter=computed(()=>selected.value&&request.value?(BigInt(selected.value.wallet.settled)+(['REDEEM','REMOVE'].includes(action.value)?-1n:1n)*BigInt(request.value.amount)).toString():'0');
const staffAfter=computed(()=>current.value&&request.value?(BigInt(current.value.wallet.settled)+(action.value==='REDEEM'?1n:-1n)*BigInt(request.value.amount)).toString():'0');
watch([newName,newUsername,newPassword,parentId],()=>{createKey.value=crypto.randomUUID();});
watch([manageAction,editName,resetPassword,manageReason],()=>{manageKey.value=crypto.randomUUID();});
const pendingKey=()=>`ng.operator.pending-transfer.v1:${current.value!.id}`;
function savePending(){try{sessionStorage.setItem(pendingKey(),JSON.stringify({actorId:current.value!.id,action:action.value,request:request.value}));}catch{throw new Error('Session storage is required to safely recover a credit request.');}}
function clearPending(){sessionStorage.removeItem(pendingKey());}
async function restorePending(){
 const raw=sessionStorage.getItem(pendingKey());if(!raw||!current.value)return;
 try{const stored=JSON.parse(raw);if(stored.actorId!==current.value.id)return;if(!['RECHARGE','REDEEM','ADD','REMOVE'].includes(stored.action)||!stored.request?.targetId)return;
 selected.value=await freshMember(stored.request.targetId);request.value=stored.request;action.value=stored.action;amount.value=credits(stored.request.amount).replaceAll(',','');reason.value=stored.request.reason;review.value=true;attempted.value=true;committed.value='';creditOpen.value=true;notice.value='An unfinished credit request was restored. Check its result using the same request ID.';
 }catch{error.value='A pending request could not be restored. Review transaction records before starting another transfer.';}
}
async function commit(){await run(async()=>{
 savePending();attempted.value=true;
 try{const result=await api<{id:string}>(action.value==='RECHARGE'?'credit-transfers':action.value==='REDEEM'?'operator/redeems':'admin/credit-adjustments',request.value);committed.value=result.id;clearPending();await load();selected.value=await freshMember(selected.value!.id);}
 catch(e){if(e instanceof ApiError&&e.status>=400&&e.status<500&&e.code!=='VERIFICATION_REQUIRED'&&e.status!==401){clearPending();request.value=null;review.value=false;attempted.value=false;selected.value=await freshMember(selected.value!.id);current.value=await refreshAccount();}throw e;}
});}
async function showReceipt(id:string){await run(async()=>{receipt.value=await api(`operator/receipts/${id}`);});}
async function verify(){await run(async()=>{await api('auth/verify',{password:verifyPassword.value});verifyPassword.value='';verifyOpen.value=false;notice.value='Verified. You can confirm your action.';});}
async function changeOwnPassword(){await run(async()=>{if(ownNewPassword.value!==ownConfirm.value)throw new Error('Passwords do not match.');await api('auth/password',{currentPassword:ownPassword.value,newPassword:ownNewPassword.value});clearPrivateState();ownConfirm.value='';notice.value='Password changed. Sign in with your new password.';});}
function printReceipt(){window.print();}
onMounted(async()=>{try{await load();await restorePending();}catch(e){if(!(e instanceof ApiError&&e.status===401))error.value=(e as Error).message;}});
</script>
<template>
 <main v-if="!current" class="login-page"><form class="login-box" @submit.prevent="login"><h1>New Game-Backend</h1><label>Account<input v-model="username" autocomplete="username" required autofocus></label><label>Password<input v-model="password" type="password" autocomplete="current-password" required></label><p v-if="error" class="error" role="alert">{{error}}</p><p v-if="notice" class="success" role="status">{{notice}}</p><button class="primary" :disabled="busy">{{busy?'Signing in…':'Login'}}</button></form></main>
 <div v-else class="operator-shell" :class="{collapsed:menu}">
  <header class="topbar"><strong class="brand">New Game-Backend</strong><button class="menu-toggle" aria-label="Toggle navigation" @click="menu=!menu">☰</button><span class="header-balance">Balance: <b>{{credits(current.wallet.available)}}</b></span><span class="identity">{{current.username}} <b>[ {{role(current.role)}} ]</b></span><button class="text-button" :disabled="busy" @click="logout">log out</button></header>
  <aside class="sidebar"><nav aria-label="Main navigation"><section v-for="group in groups" :key="group.title"><button class="group-toggle" :aria-expanded="expanded===group.title" @click="expanded=expanded===group.title?'':group.title"><span>▧</span>{{group.title}}<span class="chevron">{{expanded===group.title?'⌃':'⌄'}}</span></button><div v-if="expanded===group.title"><button v-for="item in group.items" :key="item" class="nav-item" :class="{selected:view===item}" :aria-current="view===item?'page':undefined" @click="navigate(item)">{{item}}</button></div></section></nav></aside>
  <main class="workspace" :aria-label="view">
   <p v-if="error&&!creditOpen&&!createOpen&&!manageOpen&&!verifyOpen" class="error" role="alert">{{error}}</p><p v-if="notice" class="success" role="status">{{notice}}</p>
   <template v-if="view==='Home'"><section class="home-metrics"><article v-for="(card,i) in homeCards" :key="card[0]" class="stat-card"><svg v-if="i<5" viewBox="0 0 32 32" aria-hidden="true"><circle cx="16" cy="9" r="7"/><path d="M3 30v-7q0-8 13-8t13 8v7z"/></svg><svg v-else viewBox="0 0 32 32" aria-hidden="true" class="db-icon"><ellipse cx="16" cy="7" rx="12" ry="5"/><path d="M4 7v17c0 7 24 7 24 0V7M4 15c0 7 24 7 24 0M4 22c0 7 24 7 24 0"/></svg><div><span>{{card[0]}}</span><strong>{{card[1]||'0'}}</strong></div></article></section><dl class="login-facts"><div><dt>Last login time:</dt><dd>{{date(settings?.last_login||'')}}</dd></div><div><dt>Last login IP:</dt><dd>{{settings?.lastIp||'—'}}</dd></div><div><dt>Login times:</dt><dd>{{settings?.count||'0'}}</dd></div></dl></template>
   <section v-else-if="isAccounts||isRecords||view==='Game Records'||view==='Total Account'" class="data-page">
    <div v-if="view==='Total Account'" class="report-totals"><span>Total played: <b>{{credits(totals.played)}}</b></span><span>Total win: <b>{{credits(totals.won)}}</b></span><span>Total recharge: <b>{{credits(totals.recharged)}}</b></span><span>Total redeemed: <b>{{credits(totals.redeemed)}}</b></span><span>Total income: <b>{{net(totals.recharged,totals.redeemed)}}</b></span></div>
    <div v-if="view==='Game Records'" class="report-totals"><span>Total played: <b>{{credits(rounds.played)}}</b></span><span>Total win: <b>{{credits(rounds.won)}}</b></span><span>Total played - Total win: <b>{{net(rounds.played,rounds.won)}}</b></span></div>
    <form class="filters" @submit.prevent="search"><div v-if="!isAccounts" class="filter-row"><label class="filter-label">Search by date</label><input v-model="from" aria-label="Start date (UTC)" type="date"><span>To</span><input v-model="to" aria-label="End date (UTC)" type="date" :min="from"></div><div v-if="view!=='Total Account'" class="filter-row"><select v-model="searchField" aria-label="Search field"><option>Account</option><option>Game ID</option></select><input v-model="query" placeholder="Please enter your search content" aria-label="Search content"></div><template v-if="isAccounts"><div class="filter-row"><label class="filter-label">Sort Fields:</label><select v-model="sort" aria-label="Sort fields"><option value="created">Register Time</option><option value="username">Account</option><option value="balance">Balance</option></select></div><div class="filter-row"><label class="filter-label">Sort by:</label><select v-model="order" aria-label="Sort order"><option value="desc">descend</option><option value="asc">ascend</option></select></div></template><div class="filter-buttons"><button class="primary" :disabled="busy">⌕ search</button><button type="button" :disabled="busy" @click="resetFilters">↻ Reset</button><button v-if="canCreate&&isAccounts" type="button" class="primary" :disabled="busy" @click="openCreate()">＋ create</button></div></form>
    <p v-if="isAccounts" class="table-note">Note: Recharge and redeem use available credits. Reserved credits cannot be moved.</p>
    <div class="table-scroll"><table v-if="isAccounts"><thead><tr><th>Operation</th><th>Status</th><th>Game ID</th><th>Account</th><th>Balance</th><th>Bonus</th><th>Register date</th><th>Register ip</th><th>Login times</th><th>Last login time</th><th>Last logon address</th><th>Manager</th></tr></thead><tbody><tr v-for="member in members.items" :key="member.id"><td class="operation"><button class="link" :aria-expanded="editor===member.id" @click="editor=editor===member.id?'':member.id">editor ⌄</button><div v-if="editor===member.id" class="editor-menu"><button v-if="member.canRedeem" @click="editor='';openCredit(member,'REDEEM')">Redeem</button><button v-if="canTransfer(member)" @click="editor='';openCredit(member,'RECHARGE')">Recharge</button><template v-if="member.canManage"><button @click="openManage(member,'EDIT_PROFILE')">Edit</button><button @click="openManage(member,'RESET_PASSWORD')">Reset Password</button><button @click="openManage(member,'SET_ARCHIVED')">{{member.archived?'Restore account':'Remove account'}}</button></template><template v-if="current.role==='MAIN_ADMIN'"><button @click="editor='';openCredit(member,'ADD')">Add credits</button><button @click="editor='';openCredit(member,'REMOVE')">Remove credits</button></template></div></td><td><button role="switch" :aria-checked="member.active&&!member.archived&&member.branchEnabled" :aria-label="`Status for ${member.username}`" class="switch" :class="{on:member.active&&!member.archived&&member.branchEnabled}" :disabled="busy||!member.canManage||member.archived" :title="member.archived?'Archived':!member.branchEnabled?'Branch suspended':''" @click="openManage(member,'SET_ACTIVE')"><span/></button><small v-if="member.archived">Archived</small></td><td><button v-if="member.canManage" class="link" @click="openManage(member)">{{member.publicId}}</button><span v-else>{{member.publicId}}</span></td><td>{{member.username}}</td><td>{{credits(member.wallet.available)}}</td><td>0.00</td><td>{{date(member.createdAt)}}</td><td>{{member.registeredIp||'—'}}</td><td>{{member.loginCount}}</td><td>{{date(member.lastLogin||'')}}</td><td>{{member.lastIp||'—'}}</td><td>{{member.manager||'—'}}</td></tr><tr v-if="!members.items.length"><td colspan="12" class="empty">No Data</td></tr></tbody></table>
     <table v-else-if="view==='Game Records'"><thead><tr><th>Game ID</th><th>Account</th><th>Game title</th><th>Balance before game</th><th>Total played</th><th>Total win</th><th>Balance now</th><th>Recording time</th><th>Manager</th></tr></thead><tbody><tr v-for="round in rounds.items" :key="round.id"><td>{{round.public_id}}</td><td>{{round.username}}</td><td>{{gameTitle(round.game_id)}}</td><td>{{credits(round.before_units)}}</td><td>{{credits(round.stake_units)}}</td><td>{{credits(round.award_units)}}</td><td>{{credits(round.after_units)}}</td><td>{{date(round.created_at)}}</td><td>{{round.manager||'—'}}</td></tr><tr v-if="!rounds.items.length"><td colspan="9" class="empty">No Data</td></tr></tbody></table>
     <table v-else-if="view==='Total Account'"><thead><tr><th>Agent</th><th>Actor</th><th>Total played</th><th>Total win</th><th>Total recharge</th><th>Total redeemed</th><th>Total income</th><th>Duration</th></tr></thead><tbody><tr v-for="row in totals.items" :key="row.id"><td>{{row.username}}</td><td>{{role(row.role)}}</td><td>{{credits(row.played)}}</td><td>{{credits(row.won)}}</td><td>{{credits(row.recharged)}}</td><td>{{credits(row.redeemed)}}</td><td>{{net(row.recharged,row.redeemed)}}</td><td>{{from||'All time'}}{{to?' – '+to:''}}</td></tr><tr v-if="!totals.items.length"><td colspan="8" class="empty">No Data</td></tr></tbody></table>
     <table v-else><thead><tr><th>Ticket</th><th>Game ID</th><th>Account</th><th>Before {{view==='Redeem Record'?'redeem':'recharge'}}</th><th>{{view==='Redeem Record'?'Redeemed':view==='Reward Record'?'Reward':'Recharged'}}</th><th v-if="view==='Recharge Record'">Offered</th><th>After {{view==='Redeem Record'?'redeem':'recharge'}}</th><th>IP Add</th><th>Cashier</th><th>Date</th></tr></thead><tbody><tr v-for="entry in records.items" :key="entry.id"><td><button class="link" :disabled="busy" @click="showReceipt(entry.id)">Print</button></td><td>{{entry.public_id}}</td><td>{{entry.username}}</td><td>{{credits(entry.before_units)}}</td><td>{{credits(BigInt(entry.units)<0n?(-BigInt(entry.units)).toString():entry.units)}}</td><td v-if="view==='Recharge Record'">0.00</td><td>{{credits(entry.after_units)}}</td><td>{{entry.origin_ip||'—'}}</td><td>{{entry.actor}}</td><td>{{date(entry.created_at)}}</td></tr><tr v-if="!records.items.length"><td colspan="10" class="empty">No Data</td></tr></tbody></table></div>
    <footer class="pagination"><button :disabled="busy||page<=1" @click="turnPage(-1)">prev</button><button :disabled="busy||page>=pages" @click="turnPage(1)">next</button><select v-model="pageSize" aria-label="Rows per page" :disabled="busy" @change="search"><option :value="10">10/page</option><option :value="20">20/page</option><option :value="50">50/page</option><option :value="100">100/page</option></select><label>Go to <input v-model.number="gotoPage" type="number" min="1" :max="pages" @change="turnPage((Number(gotoPage)||1)-page)"></label><span>{{total}} total</span></footer>
   </section>
   <section v-else-if="view==='Agent Rewards'" class="data-page"><nav class="tabs" aria-label="Agent Rewards"><button v-for="tab in ['Rewards','Records','Rules']" :key="tab" :class="{active:bonusTab===tab}" @click="bonusTab=tab">{{tab}}</button></nav><template v-if="bonusTab!=='Rules'"><form class="filters" @submit.prevent><div class="filter-row"><label class="filter-label">Search by date</label><input v-model="from" type="date" aria-label="Reward start date"><span>To</span><input v-model="to" type="date" aria-label="Reward end date"></div><div class="filter-row"><select aria-label="Reward search field"><option>Search Agent ID</option></select><input v-model="query" placeholder="Please enter your search content"></div><div class="filter-row"><label>Include Sub Agents</label><select v-model="includeSub"><option>Yes</option><option>No</option></select></div><div class="filter-buttons"><button class="primary">search</button><button type="button" @click="query='';from='';to='';includeSub='Yes'">Reset</button></div></form><div class="table-scroll"><table><thead><tr><th>No.</th><th>Agent Name</th><th>Account</th><th>Agent Level</th><th>Reward</th><th>Date</th><th>{{bonusTab==='Rewards'?'Status':'Collection Time'}}</th></tr></thead><tbody><tr><td colspan="7" class="empty">Agent rewards are disabled.</td></tr></tbody></table></div></template><div v-else class="panel"><h2>Rules</h2><p>Agent rewards are disabled. No rebate rate or collection schedule is active.</p></div></section>
   <section v-else-if="view==='Wager Bonus FAQ'" class="panel bonus-page"><h2>WAGER BONUS</h2><div class="filter-row"><b>Bonus Hour</b><button role="switch" aria-label="Bonus Hour" :aria-checked="false" class="switch" disabled><span/></button><span>Closed</span></div><p>Wager bonuses are disabled. No deposit-match reward or wagering requirement is active.</p><h3>FOR PLAYERS</h3><p>There is no active bonus schedule.</p></section>
   <template v-else-if="view==='Setting'&&settings"><section class="panel"><h2 class="panel-heading">Account Information</h2><div class="account-fields"><label>Agent Name<input :value="settings.account.display_name" disabled></label><label>Agent ID<input :value="settings.account.public_id" disabled></label><label>Account<input :value="settings.account.username" disabled></label><label>Agent Level<input :value="role(settings.account.role)" disabled></label><label>Login Times<input :value="settings.count" disabled></label></div></section><section class="panel"><h2 class="panel-heading">Change Password</h2><form class="password-form" @submit.prevent="changeOwnPassword"><label>Original Password<input v-model="ownPassword" type="password" autocomplete="current-password" required></label><label>New Password<input v-model="ownNewPassword" type="password" autocomplete="new-password" minlength="12" maxlength="256" required></label><div class="password-strength"><b>Password Strength</b><div class="strength-track"><span :style="{width:Math.min(100,ownNewPassword.length/12*100)+'%'}"/></div><p>{{ownNewPassword.length>=12?'✓':'○'}} At least 12 characters</p><p>Changing your password signs out all sessions and revokes API keys.</p></div><label>Confirm Password<input v-model="ownConfirm" type="password" autocomplete="new-password" required></label><button class="primary" :disabled="busy">Save Changes</button></form></section></template>
   <DevicePanel v-else-if="view==='Login Device'" :run="run" :busy="busy" :request-error="error"/>
   <ApiPanel v-else-if="view==='API Download'" :run="run" :busy="busy" :request-error="error"/>
  </main>
  <Dialog v-if="createOpen" title="Create account" :busy="busy" @close="createOpen=false"><form @submit.prevent="create"><p class="note">Every new account starts with <b>0.00 credits</b>.</p><label v-if="parentChoices.length">Manager<select v-model="parentId" required><option v-for="parent in parentChoices" :key="parent.id" :value="parent.id">{{parent.username}} ({{parent.publicId}})</option></select></label><p v-else-if="!parentId" class="error">Create a manager account first.</p><p v-else class="muted">New {{childLabel}} will belong to {{current.displayName}}.</p><label>Nickname<input v-model="newName" maxlength="100" required></label><label>Account<input v-model="newUsername" pattern="[a-z0-9][a-z0-9._-]{2,63}" autocomplete="off" required><small>3–64 lowercase letters, numbers, dots, hyphens or underscores.</small></label><label>Password<input v-model="newPassword" type="password" autocomplete="new-password" minlength="12" maxlength="256" required></label><label>Confirm password<input v-model="confirmPassword" type="password" autocomplete="new-password" required></label><p v-if="error" class="error" role="alert">{{error}}</p><footer><button type="button" :disabled="busy" @click="createOpen=false">Cancel</button><button class="primary" :disabled="busy||!parentId">Create account</button></footer></form></Dialog>
  <Dialog v-if="manageOpen&&selected" :title="`Manage ${selected.username}`" :busy="busy" @close="manageOpen=false"><form @submit.prevent="manage"><label>Action<select v-model="manageAction"><option value="EDIT_PROFILE">Edit display name</option><option value="RESET_PASSWORD">Reset password</option><option v-if="!selected.archived" value="SET_ACTIVE">{{selected.active?'Suspend account':'Reactivate account'}}</option><option value="SET_ARCHIVED">{{selected.archived?'Restore archived account':'Remove / archive account'}}</option></select></label><label v-if="manageAction==='EDIT_PROFILE'">Display name<input v-model="editName" maxlength="100" required></label><template v-if="manageAction==='RESET_PASSWORD'"><label>New password<input v-model="resetPassword" type="password" autocomplete="new-password" minlength="12" maxlength="256" required></label><label>Confirm password<input v-model="resetConfirm" type="password" autocomplete="new-password" required></label></template><p v-if="manageAction!=='EDIT_PROFILE'" class="note">This signs the account out. Suspending or archiving staff also blocks their branch. Balances and transaction history are preserved; restoring staff does not reactivate individually suspended accounts.</p><label>Reason<input v-model="manageReason" minlength="5" maxlength="500" required></label><p v-if="error" class="error" role="alert">{{error}}</p><footer><button type="button" :disabled="busy" @click="manageOpen=false">Cancel</button><button class="primary" :disabled="busy">Confirm change</button></footer></form></Dialog>
  <Dialog v-if="creditOpen&&selected" :title="actionLabel" :busy="busy" @close="creditOpen=false"><div class="target-card"><span class="avatar">{{selected.displayName.slice(0,2).toUpperCase()}}</span><span><strong>{{selected.displayName}}</strong><small>{{selected.username}}</small></span><span class="target-balance"><small>Available</small><strong>{{credits(selected.wallet.available)}}</strong></span></div><p v-if="error" class="error" role="alert">{{error}}</p><template v-if="committed"><p class="success" role="status">Transfer committed successfully.</p><p class="mono wrap">Receipt {{committed}}</p><footer><button @click="showReceipt(committed)">View receipt</button><button class="primary" @click="creditOpen=false">Done</button></footer></template><form v-else-if="!review" @submit.prevent="preview"><label>Amount in play credits<input v-model="amount" inputmode="decimal" placeholder="0.00" required></label><label>Reason<input v-model="reason" minlength="5" maxlength="500" required></label><p class="note">{{action==='RECHARGE'?`Your available credits: ${credits(current.wallet.available)}.`:`Account reserved credits: ${credits(selected.wallet.reserved)}.`}} {{action==='REDEEM'?'Available credits move back to your wallet.':''}}</p><footer><button type="button" @click="creditOpen=false">Cancel</button><button class="primary">Review transfer</button></footer></form><template v-else-if="request"><p v-if="attempted" class="note">Check this request’s result using the same ID. Retrying cannot duplicate a committed transfer.</p><dl class="details"><div><dt>Account</dt><dd>{{selected.username}}</dd></div><div><dt>Amount</dt><dd><b>{{credits(request.amount)}}</b></dd></div><template v-if="!attempted"><div><dt>Account balance</dt><dd>{{credits(selected.wallet.settled)}} → {{credits(targetAfter)}}</dd></div><div v-if="action==='RECHARGE'||action==='REDEEM'"><dt>Your balance</dt><dd>{{credits(current.wallet.settled)}} → {{credits(staffAfter)}}</dd></div></template><div><dt>Reason</dt><dd>{{request.reason}}</dd></div><div><dt>Request ID</dt><dd class="mono wrap">{{request.requestKey}}</dd></div></dl><footer><button v-if="!attempted" :disabled="busy" @click="review=false">Back</button><button class="primary" :disabled="busy" @click="commit">{{busy?'Processing…':attempted?'Check / retry request':'Confirm transfer'}}</button></footer></template></Dialog>
  <Dialog v-if="verifyOpen" title="Verify your session" :busy="busy" @close="verifyOpen=false"><p class="muted">Sensitive actions require a recent verification.</p><form @submit.prevent="verify"><label>Password<input v-model="verifyPassword" type="password" autocomplete="current-password" required></label><p v-if="error" class="error" role="alert">{{error}}</p><footer><button class="primary" :disabled="busy">Verify session</button></footer></form></Dialog>
  <Dialog v-if="receipt" title="Transaction receipt" :busy="busy" @close="receipt=null"><section class="receipt"><p class="eyebrow">NEW GAME · {{role(receipt.kind)}}</p><h3>{{receipt.username}}</h3><strong class="receipt-amount">{{credits(receipt.units)}} play credits</strong><dl class="details"><div><dt>Receipt ID</dt><dd class="mono wrap">{{receipt.id}}</dd></div><div><dt>Request ID</dt><dd class="mono wrap">{{receipt.request_id}}</dd></div><div><dt>Operator</dt><dd>{{receipt.actor}}</dd></div><div><dt>Date</dt><dd>{{date(receipt.created_at)}}</dd></div><div><dt>Reason</dt><dd>{{receipt.reason}}</dd></div><div><dt>Before → After</dt><dd>{{credits(receipt.before_units)}} → {{credits(receipt.after_units)}}</dd></div><div><dt>Wallet version</dt><dd>{{receipt.wallet_version}}</dd></div></dl><template v-if="receipt.round_id"><h3>Committed game round</h3><dl class="details"><div><dt>Game</dt><dd>{{receipt.game_id}}</dd></div><div><dt>Round ID</dt><dd class="mono wrap">{{receipt.round_id}}</dd></div><div><dt>Stake / Award</dt><dd>{{credits(receipt.stake_units!)}} / {{credits(receipt.award_units!)}}</dd></div><div><dt>Rules version</dt><dd>{{receipt.profile_id}}</dd></div></dl></template><h3>Visible wallet entries</h3><div v-for="posting in receipt.postings" :key="posting.username" class="summary-row"><span>{{posting.username}}</span><b>{{credits(posting.units)}}</b></div></section><footer class="no-print"><button @click="receipt=null">Close</button><button class="primary" @click="printReceipt">Print receipt</button></footer></Dialog>
 </div>
</template>
