<script setup lang="ts">
import {nextTick,ref} from 'vue';
import WinBurst from '../../apps/player/src/WinBurst.vue';

import {winStyles} from '../../apps/player/src/win-effects';
const epoch=ref(0),reduced=ref(false),status=ref('Ready'),panels=ref(['disco-diamonds','ember-relics','aurora-vault','orchard-numbers','royal-blackjack','abyss-legends']);
async function preview(peak=false){epoch.value++;status.value=peak?'Frozen at peak for visual inspection':'Playing finite effects';await nextTick();if(peak)requestAnimationFrame(()=>{for(const animation of document.querySelector('.effect-samples')!.getAnimations({subtree:true})){animation.pause();animation.currentTime=900;}});}
</script>
<template><main class="effect-check"><h1>Local win effects acceptance</h1><p>Render fixtures only · no account, stake, game request or credit award. This page is excluded from the production build.</p><nav><button @click="preview()">Replay effects</button><button @click="preview(true)">Inspect at peak</button><label><input type="checkbox" v-model="reduced">Reduced motion</label><output>{{status}}</output></nav><div class="effect-samples"><section v-for="(game,index) in panels" :key="index" :style="{background:`radial-gradient(ellipse at 50% 40%,${winStyles[game].accent}30,#101422 68%)`}"><label>Game <select v-model="panels[index]"><option v-for="name in Object.keys(winStyles)" :key="name">{{name}}</option></select></label><h2>{{game.replaceAll('-',' ').toUpperCase()}}</h2><div class="effect-symbol">{{winStyles[game].glyph}}</div><WinBurst :key="`${game}-${epoch}`" :game="game" :id="`fixture-${epoch}`" award="500" stake="25" :running="true" :reduced-motion="reduced" :numbers="game.includes('numbers')?[7,12,24,38]:undefined"/><output class="fixture-return">WIN 5.00</output></section></div></main></template>
<style>body{margin:0;background:#080d16;color:#eee7ce;font:14px Arial}.effect-check{padding:18px}.effect-check h1{margin:0;font:700 24px Georgia}.effect-check p{color:#bbbdc7;font-size:12px}.effect-check nav{display:flex;align-items:center;gap:15px;margin-bottom:16px}.effect-check button,.effect-check select{background:#263444;color:#fff1bd;border:1px solid #b09a61;border-radius:5px;padding:8px}.effect-check output{color:#d9bca4}.effect-samples{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.effect-samples>section{position:relative;height:295px;border:1px solid #ad9557;border-radius:12px;overflow:hidden;padding:12px}.effect-samples label{position:relative;z-index:20;display:block;font-size:11px}.effect-samples h2{font:700 14px Georgia;letter-spacing:1px;text-align:center}.effect-symbol{text-align:center;font:800 56px Georgia;color:#f6d16c;padding:8px;text-shadow:0 0 35px #ecb45466}.effect-samples .fixture-return{position:absolute;bottom:5px;left:5px;right:5px;margin:0;padding:8px}.effect-samples .win-burst{inset:35px 0 62px}.effect-samples .win-particle{--size:20px!important}@media(max-width:800px){.effect-samples{grid-template-columns:repeat(2,1fr)}}@media(max-width:480px){.effect-samples{grid-template-columns:1fr}.effect-check nav{flex-wrap:wrap}}</style>
