import { test,after } from 'node:test';
import assert from 'node:assert/strict';
import { readFile,readdir } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import pg from 'pg';
if(!process.env.DATABASE_URL)throw new Error('A local PostgreSQL DATABASE_URL is required; database tests are not simulated.');
const url=new URL(process.env.DATABASE_URL);if(!['127.0.0.1','localhost'].includes(url.hostname)||!/^\/new_game_(dev|test)$/.test(url.pathname))throw new Error('Tests only run against local development databases.');
const schema=`test_${randomUUID().replaceAll('-','')}`;const control=new pg.Client({connectionString:process.env.DATABASE_URL});await control.connect();await control.query(`CREATE SCHEMA ${schema}`);await control.query(`SET search_path TO ${schema}`);
for(const file of (await readdir('database/migrations')).filter(f=>f.endsWith('.sql')).sort())await control.query(await readFile(`database/migrations/${file}`,'utf8'));
process.env.PGOPTIONS=`-c search_path=${schema}`;
const {passwordHash,newTotpSecret,totp}=await import('../../dist/server/apps/api/src/security.js');
const {createApi}=await import('../../dist/server/apps/api/src/app.js');
const {pool}=await import('../../dist/server/apps/api/src/store.js');
const adminId=randomUUID(),branch=randomUUID(),adminPassword='LocalTestPassword-1234',secret=newTotpSecret();
await control.query('INSERT INTO branches(id,name) VALUES($1,$2)',[branch,'Test root']);await control.query('INSERT INTO branch_ancestors VALUES($1,$1,0)',[branch]);
await control.query("INSERT INTO accounts(id,branch_id,role,display_name,active,username,password_hash,totp_secret) VALUES($1,$2,'MAIN_ADMIN','Test admin',true,'test.admin',$3,$4)",[adminId,branch,await passwordHash(adminPassword),secret]);await control.query('INSERT INTO wallets(id,account_id) VALUES($1,$2)',[randomUUID(),adminId]);
const app=await createApi();await app.listen(0,'127.0.0.1');const base=await app.getUrl();
async function call(path,body,auth,extra={}){const response=await fetch(`${base}/v1/${path}`,{method:body===undefined?'GET':'POST',headers:{Origin:'http://127.0.0.1:5174','Content-Type':'application/json',...(auth?{Cookie:auth.cookie,'X-CSRF-Token':auth.csrf}:{}),...extra},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:response.status,data:await response.json(),cookie:response.headers.get('set-cookie')?.split(';')[0]};}
async function signin(username,password=adminPassword,code){const response=await call('auth/login',{username,password,...(code?{code}:{})});assert.equal(response.status,201,JSON.stringify(response.data));return {cookie:response.cookie,csrf:response.data.csrf};}
const admin=await signin('test.admin',adminPassword,totp(secret));
let north,agent,player,peer,south,southAgent,southPlayer,operator,playerAuth,peerAuth,southAuth;
async function create(parentId,username){const response=await call('admin/accounts',{parentId,username,displayName:username,password:adminPassword},admin);assert.equal(response.status,201,JSON.stringify(response.data));return response.data.id;}
async function snapshot(auth){const response=await call('me',undefined,auth);assert.equal(response.status,200,JSON.stringify(response.data));return response.data;}
async function wallet(id){const r=await call('admin/accounts',undefined,admin);return r.data.find(a=>a.id===id).wallet;}
async function adjust(id,direction,amount,key=randomUUID(),expectedVersion){const w=await wallet(id);return call('admin/credit-adjustments',{targetId:id,direction,amount,reason:'Explicit manual test adjustment',requestKey:key,expectedVersion:expectedVersion??w.version},admin);}
test('full account, ledger and practice flow against PostgreSQL',async t=>{
 await t.test('creates strict hierarchy and all wallets at zero',async()=>{north=await create(adminId,'north');agent=await create(north,'north.agent');player=await create(agent,'north.player');peer=await create(agent,'north.peer');south=await create(adminId,'south');southAgent=await create(south,'south.agent');southPlayer=await create(southAgent,'south.player');operator=await signin('north.agent');playerAuth=await signin('north.player');peerAuth=await signin('north.peer');southAuth=await signin('south.player');assert.equal((await snapshot(playerAuth)).wallet.available,'0');assert.ok((await control.query('SELECT * FROM wallets')).rows.every(w=>w.settled_units==='0'));});
 await t.test('rejects wrong passwords, missing MFA, forged role and cross-branch reads',async()=>{assert.equal((await call('auth/login',{username:'test.admin',password:adminPassword})).status,401);assert.equal((await call('auth/login',{username:'north.player',password:'wrong'})).status,401);assert.equal((await call('admin/accounts',undefined,playerAuth)).status,403);assert.equal((await call(`history?accountId=${southPlayer}`,undefined,operator)).status,404);assert.equal((await call(`history?accountId=${peer}`,undefined,playerAuth)).status,404);const rows=(await call('admin/accounts',undefined,operator)).data;assert.ok(rows.every(r=>r.id!==southPlayer&&r.id!==south));});
 await t.test('manual ADD is balanced, durable and idempotent under simultaneous retries',async()=>{const key=randomUUID(),version=(await wallet(player)).version;const attempts=await Promise.all(Array.from({length:8},()=>adjust(player,'ADD','10000',key,version)));assert.ok(attempts.every(r=>r.status===201),JSON.stringify(attempts));assert.equal(new Set(attempts.map(r=>r.data.id)).size,1);assert.equal((await wallet(player)).settled,'10000');assert.equal((await adjust(player,'ADD','999',key,version)).status,409);assert.equal((await control.query('SELECT sum(units)::text total FROM ledger_postings')).rows[0].total,'0');});
 await t.test('competing removals cannot overspend and stale previews fail',async()=>{const version=(await wallet(player)).version;const attempts=await Promise.all([adjust(player,'REMOVE','7000',randomUUID(),version),adjust(player,'REMOVE','7000',randomUUID(),version)]);assert.deepEqual(attempts.map(r=>r.status).sort(),[201,409]);assert.equal((await wallet(player)).settled,'3000');assert.equal((await adjust(player,'REMOVE','4000')).status,409);});
 await t.test('privileged verification and CSRF are enforced server-side',async()=>{const data={targetId:player,direction:'ADD',amount:'1',reason:'Explicit test attempt',requestKey:randomUUID(),expectedVersion:(await wallet(player)).version};assert.equal((await call('admin/credit-adjustments',data,playerAuth)).status,403);assert.equal((await call('admin/credit-adjustments',data,admin,{'X-CSRF-Token':'wrong'})).status,403);assert.equal((await call('admin/credit-adjustments',data,admin,{Origin:'https://untrusted.invalid'})).status,403);await control.query("UPDATE sessions SET verified_at=now()-interval '10 minutes' WHERE account_id=$1",[adminId]);assert.equal((await call('admin/credit-adjustments',data,admin)).status,403);assert.equal((await call('auth/verify',{password:adminPassword,code:totp(secret)},admin)).status,201);});
 await t.test('branch transfers move owned supply and forbid sibling branches and players',async()=>{assert.equal((await adjust(agent,'ADD','5000')).status,201);const source=await wallet(agent),target=await wallet(player),key=randomUUID();const data={targetId:player,amount:'2000',reason:'Branch distribution test',expectedVersion:source.version,targetVersion:target.version,requestKey:key};const results=await Promise.all([call('credit-transfers',data,operator),call('credit-transfers',data,operator)]);assert.ok(results.every(r=>r.status===201),JSON.stringify(results));assert.equal(results[0].data.id,results[1].data.id);assert.equal((await wallet(agent)).settled,'3000');assert.equal((await wallet(player)).settled,'5000');assert.equal((await call('credit-transfers',{...data,targetId:southPlayer,requestKey:randomUUID()},operator)).status,404);assert.equal((await call('credit-transfers',data,playerAuth)).status,403);});
 await t.test('reversals append linked entries, never erase or create hidden debt',async()=>{const added=await adjust(peer,'ADD','1000');const data={transactionId:added.data.id,reason:'Correct explicit test addition',requestKey:randomUUID(),expectedVersion:(await wallet(peer)).version};const reversed=await call('admin/reversals',data,admin);assert.equal(reversed.status,201,JSON.stringify(reversed));assert.equal((await wallet(peer)).settled,'0');assert.equal((await call('admin/reversals',{...data,requestKey:randomUUID()},admin)).status,409);assert.equal((await call('history',undefined,peerAuth)).data.length,2);});
 await t.test('database rejects unbalanced transactions, history edits and direct balance overwrite',async()=>{await assert.rejects(()=>control.query('UPDATE wallets SET settled_units=settled_units+1 WHERE account_id=$1',[player]),/reconcile/);await assert.rejects(()=>control.query('DELETE FROM ledger_postings'),/immutable/);await assert.rejects(()=>control.query("INSERT INTO ledger_transactions(id,actor_id,target_id,branch_id_at_event,kind,reason,request_id) VALUES($1,$2,$3,$4,'MANUAL_ADD','Unbalanced test','bad-key')",[randomUUID(),adminId,player,branch]),/balanced/);});
 await t.test('server practice rounds persist one result per request and never change credits',async()=>{const before=await wallet(player);const body={requestKey:randomUUID()};const spins=await Promise.all([call('practice/temple-lights/rounds',body,playerAuth),call('practice/temple-lights/rounds',body,playerAuth)]);assert.equal(spins[0].status,201,JSON.stringify(spins));assert.deepEqual(spins[0].data,spins[1].data);assert.equal(spins[0].data.grid.length,3);assert.ok(spins[0].data.grid.every(row=>row.length===5));assert.deepEqual(await wallet(player),before);const draw=await call('practice/orchard-numbers/rounds',{requestKey:randomUUID(),picks:[1,2,3,4]},peerAuth);assert.equal(draw.status,201,JSON.stringify(draw));assert.equal(new Set(draw.data.drawn).size,20);assert.ok(draw.data.hits.every(n=>draw.data.drawn.includes(n)&&[1,2,3,4].includes(n)));assert.equal((await call('games/temple-lights/rounds',{},playerAuth)).status,409);});
 await t.test('new cabinet rounds persist once under concurrent retries and never change the wallet',async()=>{
  for(const game of ['neon-sevens','jade-fortune','coin-carnival']){
   await new Promise(resolve=>setTimeout(resolve,550));
   const before=await wallet(player),body={requestKey:randomUUID()};
   const attempts=await Promise.all(Array.from({length:5},()=>call(`practice/${game}/rounds`,body,playerAuth)));
   assert.ok(attempts.every(r=>r.status===201),JSON.stringify(attempts));
   for(const attempt of attempts)assert.deepEqual(attempt.data,attempts[0].data);
   const result=attempts[0].data;
   assert.equal(result.ruleVersion,'practice-v1');assert.equal(result.creditsChanged,false);
   assert.ok(result.frames.length>=1&&result.frames.length<=(game==='coin-carnival'?4:1));
   assert.deepEqual(await wallet(player),before);
   assert.equal((await control.query('SELECT count(*)::int n FROM practice_rounds WHERE account_id=$1 AND request_key=$2',[player,body.requestKey])).rows[0].n,1);
   assert.deepEqual((await call('practice/history',undefined,playerAuth)).data[0].result,result);
   for(const field of [{award:'100'},{grid:[]},{seed:1},{picks:[1,2,3,4]}])assert.equal((await call(`practice/${game}/rounds`,{...body,...field},playerAuth)).status,400);
   assert.equal((await call(`practice/${game}/rounds`,{requestKey:randomUUID()},operator)).status,403);
   assert.equal((await call(`practice/${game}/rounds`,{requestKey:randomUUID()},playerAuth,{'X-CSRF-Token':'invalid'})).status,403);
   assert.equal((await call('practice/temple-lights/rounds',body,playerAuth)).status,409);
   assert.equal((await call(`games/${game}/rounds`,{},playerAuth)).status,409);
  }
 });
 await t.test('feature practice sequences persist atomically, replay unchanged and cannot touch credits',async()=>{
  for(const game of ['aurora-vault','ember-relics']){
   await new Promise(resolve=>setTimeout(resolve,550));
   const before=await wallet(player), body={requestKey:randomUUID()};
   const attempts=await Promise.all(Array.from({length:5},()=>call(`practice/${game}/rounds`,body,playerAuth)));
   assert.ok(attempts.every(r=>r.status===201),JSON.stringify(attempts));
   for(const attempt of attempts)assert.deepEqual(attempt.data,attempts[0].data);
   const result=attempts[0].data;
   assert.equal(result.ruleVersion,'practice-v1');assert.equal(result.creditsChanged,false);
   assert.equal(result.sequence.kind,game==='aurora-vault'?'vault':'cascade');
   assert.deepEqual(await wallet(player),before);
   assert.equal((await control.query('SELECT count(*)::int n FROM practice_rounds WHERE account_id=$1 AND request_key=$2',[player,body.requestKey])).rows[0].n,1);
   assert.deepEqual((await call('practice/history',undefined,playerAuth)).data[0].result,result);
   assert.equal((await call(`practice/${game}/rounds`,{...body,award:'100'},playerAuth)).status,400);
   assert.equal((await call(`practice/${game}/rounds`,{...body,picks:[1,2,3,4]},playerAuth)).status,400);
   assert.equal((await call(`practice/${game}/rounds`,{requestKey:randomUUID()},operator)).status,403);
   assert.equal((await call(`practice/${game}/rounds`,{requestKey:randomUUID()},playerAuth,{'X-CSRF-Token':'invalid'})).status,403);
   assert.equal((await call(`practice/${game==='aurora-vault'?'ember-relics':'aurora-vault'}/rounds`,body,playerAuth)).status,409);
   assert.equal((await call(`games/${game}/rounds`,{},playerAuth)).status,409);
  }
 });
 await t.test('four-seat practice rooms enforce branch separation and single capture',async()=>{const first=await call('practice/reef/join',{},playerAuth),second=await call('practice/reef/join',{},peerAuth),other=await call('practice/reef/join',{},southAuth);assert.equal(first.status,201,JSON.stringify(first));assert.equal(first.data.id,second.data.id);assert.notEqual(first.data.seat,second.data.seat);assert.notEqual(first.data.id,other.data.id);await new Promise(resolve=>setTimeout(resolve,550));const attempts=await Promise.all([playerAuth,peerAuth].map(auth=>call('practice/reef/shots',{roomId:first.data.id,targetId:1,requestKey:randomUUID()},auth)));assert.ok(attempts.every(r=>r.status===201),JSON.stringify(attempts));assert.equal(attempts.filter(r=>r.data.captured).length,1);assert.equal((await call('practice/reef/shots',{roomId:first.data.id,targetId:2,requestKey:randomUUID()},southAuth)).status,409);assert.equal((await call('practice/reef/room',undefined,playerAuth)).data.seats.length,2);});
 await t.test('manual removal preserves reserved amounts',async()=>{const prior=await wallet(player);await control.query('UPDATE wallets SET reserved_units=4000 WHERE account_id=$1',[player]);assert.equal((await adjust(player,'REMOVE','2000')).status,409);assert.equal((await wallet(player)).settled,prior.settled);assert.equal((await wallet(player)).reserved,'4000');await control.query('UPDATE wallets SET reserved_units=0 WHERE account_id=$1',[player]);});
 await t.test('account management revokes sessions, preserves credits and requires root authority',async()=>{const before=await wallet(peer);const body={action:'SET_ACTIVE',active:false,reason:'Manual account access test'};assert.equal((await call(`admin/accounts/${peer}/manage`,body,operator)).status,403);assert.equal((await call(`admin/accounts/${peer}/manage`,body,admin)).status,201);assert.equal((await call('me',undefined,peerAuth)).status,401);assert.equal((await call('auth/login',{username:'north.peer',password:adminPassword})).status,401);assert.equal((await call(`admin/accounts/${peer}/manage`,{...body,active:true},admin)).status,201);assert.equal((await call(`admin/accounts/${peer}/manage`,{action:'RESET_PASSWORD',password:'ReplacementPassword-456',reason:'Manual password recovery test'},admin)).status,201);assert.equal((await call('auth/login',{username:'north.peer',password:adminPassword})).status,401);await signin('north.peer','ReplacementPassword-456');assert.deepEqual(await wallet(peer),before);assert.equal((await call('admin/audit',undefined,operator)).status,403);assert.ok((await call('admin/audit',undefined,admin)).data.some(row=>row.event_type==='RESET_PASSWORD'));});
 await t.test('logout revokes persistent session',async()=>{assert.equal((await call('auth/logout',{},playerAuth)).status,201);assert.equal((await call('me',undefined,playerAuth)).status,401);});
});
after(async()=>{await app.close();await pool.end();await control.query(`DROP SCHEMA ${schema} CASCADE`);await control.end();});
