import { test,expect } from '@playwright/test';
import { readFile,mkdir } from 'node:fs/promises';
import { totp } from '../../apps/api/src/security';
async function credentials(){const users=JSON.parse(await readFile('.local/player-credentials.json','utf8'));return users.accounts.find((account:{username:string})=>account.username==='player.one');}
async function screenshot(page:import('@playwright/test').Page,name:string){await mkdir('reports/screenshots-v2',{recursive:true});await page.screenshot({path:`reports/screenshots-v2/${name}.png`,fullPage:true,animations:'disabled'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
test('player login, persisted practice results, recovery and logout',async({page},info)=>{
 const account=await credentials();await page.goto('/');await expect(page.getByRole('heading',{name:'WELCOME BACK'})).toBeVisible();await screenshot(page,`login-${info.project.name}`);
 await page.getByLabel('PLAYER ID',{exact:true}).fill(account.username);await page.getByLabel('PASSWORD',{exact:true}).fill(account.password);await page.getByRole('button',{name:'SIGN IN',exact:true}).click();
 await expect(page.locator('.compact-brand')).toContainText('Player One');await page.getByRole('button',{name:'Explore Temple Lights'}).click();await page.getByRole('button',{name:'Spin practice'}).click();await expect(page.getByRole('button',{name:'Spin practice'})).toBeEnabled();await expect(page.locator('.preview-notice')).toContainText(/matching|matched/);
 await page.reload();await expect(page.locator('.compact-brand')).toContainText('Player One');await page.getByRole('button',{name:'Explore Temple Lights'}).click();await expect(page.locator('.preview-notice')).toContainText('Last saved round:');await screenshot(page,`practice-slots-${info.project.name}`);
 await page.getByRole('button',{name:'Back to arcade'}).click();await page.getByRole('button',{name:'Explore Orchard Numbers'}).click();await page.getByRole('button',{name:'Quick pick'}).click();await page.getByRole('button',{name:'Draw practice'}).click();await expect(page.locator('.keno-board .drawn')).toHaveCount(20);await expect(page.locator('.preview-notice')).toContainText('numbers matched');
 await page.getByRole('button',{name:'Back to arcade'}).click();await page.getByRole('button',{name:'HISTORY',exact:true}).click();await expect(page.locator('.player-history-row').first()).toContainText('orchard-numbers');await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'SIGN OUT',exact:true}).click();await expect(page.getByRole('heading',{name:'WELCOME BACK'})).toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:'WELCOME BACK'})).toBeVisible();
});
test('administrator commits and reverses an explicit local test adjustment',async({page},info)=>{
 const admin=JSON.parse(await readFile('.local/admin-credentials.json','utf8'));await page.goto('http://127.0.0.1:5174');await page.getByLabel('Staff ID',{exact:true}).fill(admin.username);await page.getByLabel('Password',{exact:true}).fill(admin.password);await page.getByLabel(/Authenticator code/).fill(totp(admin.totpSecret));await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'People & play credits'})).toBeVisible();
 await page.getByRole('button').filter({hasText:'Player One'}).click();await expect(page.locator('.detail-identity')).toContainText('Player One');await screenshot(page,`admin-accounts-${info.project.name}`);
 await page.getByRole('button',{name:'Add credits',exact:true}).click();await page.getByLabel('Amount in play credits').fill('1.00');await page.getByLabel('Reason for adjustment').fill('Manual local browser acceptance test');await page.getByRole('button',{name:'Review adjustment'}).click();await screenshot(page,`admin-review-${info.project.name}`);await page.getByRole('button',{name:'Confirm adjustment'}).click();await expect(page.getByRole('dialog')).toContainText('Saved successfully.');await page.getByRole('button',{name:'Done',exact:true}).click();
 await page.getByRole('button',{name:'Remove credits',exact:true}).click();await page.getByLabel('Amount in play credits').fill('1.00');await page.getByLabel('Reason for adjustment').fill('Remove explicit local test addition');await page.getByRole('button',{name:'Review adjustment'}).click();await page.getByRole('button',{name:'Confirm adjustment'}).click();await expect(page.getByRole('dialog')).toContainText('Saved successfully.');await page.getByRole('button',{name:'Done',exact:true}).click();await expect(page.locator('.balance-split')).toContainText('0.00');await page.getByRole('button',{name:'Sign out',exact:true}).click();
});
test('two real players share the same practice fishing table',async({page,browser},info)=>{
 test.setTimeout(60000);
 const users=JSON.parse(await readFile('.local/player-credentials.json','utf8')).accounts;
 const otherContext=await browser.newContext({viewport:page.viewportSize()!});const other=await otherContext.newPage();
 try{
  for(const [tab,name] of [[page,'player.one'],[other,'player.two']] as const){const user=users.find((item:{username:string})=>item.username===name);await tab.goto('http://127.0.0.1:5173');await tab.getByLabel('PLAYER ID',{exact:true}).fill(name);await tab.getByLabel('PASSWORD',{exact:true}).fill(user.password);await tab.getByRole('button',{name:'SIGN IN',exact:true}).click();await tab.getByRole('button',{name:'Explore Reef Party'}).click();await tab.locator('.fish-table-card').first().getByRole('button',{name:/JOIN TABLE|OPEN TABLE|RETURN TO TABLE/}).click();await expect(tab.locator('.reef-console')).toContainText('CREDITS',{timeout:15000});}
  await expect(other.locator('.reef-seat-plaque.yours')).toContainText('Player Two');await other.bringToFront();await expect(other.locator('.reef-deluxe')).toContainText('Player One');await page.bringToFront();await expect(page.locator('.reef-deluxe')).toContainText('Player Two');await expect(page.locator('.reef-deluxe')).toContainText('Open seat');await screenshot(page,`practice-fishing-${info.project.name}`);
 }finally{await otherContext.close();}
});
