<script setup lang="ts">
import {computed} from 'vue';
import {cabinetGames,cabinetBase,isCabinetGame,cabinetExpansionProfile,reefTierProfile,stagingRules,stakeLimits,isFishGame,type StagingGame} from '@new-game/game-math';
import ArcadeSymbol from './ArcadeSymbol.vue';
const props=defineProps<{game:StagingGame;staked:boolean}>();
const instructions:Record<StagingGame,string[]>={
 'disco-diamonds':['Three reels and five active paylines. Match all three symbols on a line.','Disco diamonds use the gem award. Cherry 1×, bell/BAR 2×, diamond 3× and seven 5×; add all winning lines.'],
 'midnight-express':['An upright five-reel cabinet with nine active paylines. Play in portrait on phones.','The locomotive is WILD. It substitutes in left-to-right runs of at least three symbols. An all-locomotive run pays once on its line.'],
 'pirate-gold':['Center-row doubloons lock their entire reel. The other reels respin up to three times with no extra stake.','Collect all five doubloons for the existing 5× return. New locks do not reset the respin counter.'],
 'sunken-dynasty':['Choose one of four jade cannons. Koi and shrimp are small; lionfish and cuttlefish medium; turtles and sentinel crabs large; the dynasty dragon and sea empress are bosses.','Capture a boss to reveal its committed 20× award on the jackpot wheel. Auto, lock, rapid firing and solo bot assistance work exactly as in Reef Party.'],
 'polar-odyssey':['Choose a crystal cannon. Icefish and shrimp are small; seals and squid medium; narwhals and snow crabs large; glacial serpents and crystal orcas are bosses.','Boss wheels reveal the existing 20× award. Small creatures arrive between larger targets, with one boss at a time.'],
 'neon-numbers':['Choose 4–10 numbers from 1–80. Twenty numbers reveal in sequence. Quick Pick selects six editable numbers.','Uses the same test paytable as Orchard Numbers. There is no separate bonus stake.'],
 'pearl-keno':['Choose 4–10 numbered pearls from 1–80. Twenty pearls reveal. Matching selected pearls are highlighted.','Uses the same test paytable as Orchard Numbers. There is no additional bonus pool.'],
 'abyss-legends':['Choose one of four seats in the Abyss Lounge. Each player controls their own cannon and stake.','Aim, click to fire, or enable AUTO and LOCK. Lantern anglers, leafy seadragons, armored sharks, krakens and leviathans use the same size-based rewards as Reef Party.','A treasure chest is a medium target. Catching it reveals its 3× award. Boss catches show a jackpot wheel celebrating the committed 20× award. These animations add no extra stake, payout or progressive pool.'],
 'ruby-rush':['Three reels, three rows. Choose your stake and press SPIN. All five paylines are active.','Match all three symbols on a line. Red diamonds use the gem award. The line review highlights each winning path in turn.'],
 'sapphire-crown':['Play in portrait orientation. Choose your stake and press SPIN. All nine paylines are active.','The crown is WILD. It substitutes in left-to-right runs of three or more; an all-crown run pays once on each line.'],
 'solar-fortune':['Five reels show a single row of symbols. A sun coin locks its reel. Choose your stake and press SPIN.','Only unlocked reels respin, up to three times, with no additional stake. New locks do not reset the counter. Collect all five sun coins to win.'],
 'neon-sevens':['Three reels, three rows. Choose your stake, then press SPIN. All five paylines are active.','Match all three symbols on a line. Use LINE MAP to see the five paths.'],
 'jade-fortune':['Choose your stake, then press SPIN. All nine paylines are active.','The dragon is wild and substitutes for any matching symbol. Matches run from the leftmost reel across adjacent reels.'],
 'coin-carnival':['Choose your stake and start a spin. A coin in the middle row locks its whole reel.','The unlocked reels respin up to three times at no additional stake. Collect coins on all five reels to win.'],
 'temple-lights':['Choose your stake and press SPIN. The three horizontal rows are active.','Match three or more of the same symbol on adjacent reels, starting at the left edge.'],
 'aurora-vault':['Play in portrait orientation. Start with three crystals already locked in a 3-column, 5-row vault.','You have three pulses. New crystals stay locked and reset the remaining pulses to three. The sequence ends when the vault is full or no pulses remain.'],
 'ember-relics':['Start a sequence on the 6 × 5 relic board. Groups of four or more matching relics connected horizontally or vertically clear together.','New relics fall into the gaps. The sequence continues until no group remains, with a maximum of six clearing cascades. Diagonal connections do not count.'],
 'orchard-numbers':['Select 4–10 different numbers from 1–80, then press DRAW. Twenty different numbers are drawn.','QUICK PICK selects six numbers you can change. CLEAR removes your selection. A hit is one of your selected numbers appearing in the draw.'],
 'reef-party':['Choose a table and one of four player seats. Aim and click or tap for each shot. Several shots can travel at once; each valid hit uses the cannon stake selected when it was fired.','AUTO keeps firing in your aim direction. LOCK tracks a creature; tap another creature to change targets. FAST doubles the automatic firing cadence. Turning it on does not change capture chances or rewards.','Only a server-validated hit spends credits. Shots that miss, expire, or reach an already-caught creature cost nothing. A resisted hit still spends its stake.','Each valid hit has an independent capture chance. Larger creatures pay more and usually need more hits, but there is no fixed health bar or guaranteed number of shots.','Treasure chests use the medium tier (3×); boss wheel animations reveal the existing 20× catch award. There is no additional wheel stake or jackpot pool.','Auto fire stops when you pause, leave the table, change stake, lose connection, or have insufficient credits. Catch celebrations show the existing award; there is no separate progressive jackpot.']
};
const lines=computed(()=>isCabinetGame(props.game)?cabinetGames[props.game].lines:props.game==='temple-lights'?[[0,0,0,0,0],[1,1,1,1,1],[2,2,2,2,2]]:[]);
const cabinet=computed(()=>isCabinetGame(props.game)?cabinetGames[props.game]:null);
const baseGame=computed(()=>isCabinetGame(props.game)?cabinetBase(props.game):null);
const themed=computed(()=>Object.hasOwn(cabinetExpansionProfile.rules,props.game));
function symbolName(symbol:string){if(props.game==='midnight-express')return ({dragon:'Locomotive · WILD',coin:'Ticket',lotus:'Pocket watch',gem:'Sapphire',bell:'Whistle',leaf:'Luggage',seven:'Lantern'} as Record<string,string>)[symbol];if(props.game==='pirate-gold')return ({coin:'Doubloon · HOLD',cherry:'Compass',bell:'Skull',bar:'Ship',seven:'Treasure map'} as Record<string,string>)[symbol];if(props.game==='disco-diamonds'&&symbol==='gem')return 'Disco diamond';if(props.game==='sapphire-crown')return ({dragon:'Crown · WILD',coin:'Sun coin',lotus:'Crystal lotus',gem:'Amethyst',bell:'Scepter',leaf:'Treasure pouch',seven:'Star'} as Record<string,string>)[symbol];if(props.game==='solar-fortune')return ({coin:'Sun coin · HOLD',cherry:'Planet',bell:'Moon',bar:'Star',seven:'Phoenix'} as Record<string,string>)[symbol];return symbol==='gem'&&themed.value?'Ruby':symbol.toUpperCase();}
function returns(symbol:string,count:number){return baseGame.value==='neon-sevens'?({cherry:1,bell:2,bar:2,gem:3,seven:5}[symbol]||0)*({3:1,4:2,5:4}[count]||0):({3:2,4:4,5:8}[count]||0);}
const matchCounts=computed(()=>cabinet.value?.columns===3?[3]:[3,4,5]);
const tiers=Object.values(reefTierProfile.tiers);
</script>
<template>
 <div class="game-rules">
  <p class="rules-mode">{{staked?'PLAY CREDITS':'GUEST / FREE PREVIEW'}} <span>• No cash or prizes of value</span></p>
  <h3>HOW TO PLAY</h3>
  <ol><li v-for="instruction in instructions[game]" :key="instruction">{{instruction}}</li></ol>
  <section class="rules-return"><h3>{{isFishGame(game)?'CREATURE RETURNS':'WINNING RETURNS'}}</h3>
   <template v-if="isFishGame(game)">
    <p>When you are the only human at the table, three labeled bot teammates assist each paid hit. If your first attempt fails, they take up to three free attempts using the same tier chance, stopping at the first capture. You receive at most one tier award. Bots stop when another human joins; they never spend credits or claim awards themselves. Their independent shots at other creatures are visual activity only: those shots do not remove creatures or award credits. The paid-hit solo assistance above is unchanged.</p><table><thead><tr><th>Size</th><th>Return</th><th>Per attempt</th><th>With solo assists</th></tr></thead><tbody><tr v-for="tier in tiers" :key="tier.label"><th>{{tier.label}}</th><td>{{tier.multiplier}}× stake</td><td>{{tier.captureTickets/100}}%</td><td>{{(100*(1-(1-tier.captureTickets/10000)**4)).toFixed(2)}}%</td></tr></tbody></table>
    <p>At a 0.25 stake, a successful small, medium, large or boss catch returns 0.25, 0.75, 2.00 or 5.00 credits respectively. Open SPECIES at the table to see each creature’s size tier.</p>
   </template>
   <p v-else>{{stagingRules[game]}}</p>
   <p>Multipliers apply to the total selected stake. Returns include any returned stake; they are not extra profit on top of it. An unsuccessful paid play returns zero.</p>
  </section>
  <table v-if="cabinet && baseGame!=='coin-carnival'" class="symbol-paytable"><thead><tr><th>Symbol</th><th v-for="count in matchCounts" :key="count">{{count}}</th></tr></thead><tbody><tr v-for="symbol in cabinet.symbols" :key="symbol"><th><ArcadeSymbol :symbol="symbol" :theme="game"/><span>{{symbolName(symbol)}}</span></th><td v-for="count in matchCounts" :key="count">{{returns(symbol,count)}}×</td></tr></tbody></table>
  <div v-if="lines.length" class="rules-lines" aria-label="Active payline paths"><figure v-for="(line,index) in lines" :key="index"><svg :viewBox="`0 0 ${line.length*20} 60`" role="img" :aria-label="`Line ${index+1}: rows ${line.map(row=>row+1).join(', ')}`"><path :d="`M0 20H${line.length*20}M0 40H${line.length*20}`" stroke="#ffffff25" fill="none"/><polyline :points="line.map((row,col)=>`${col*20+10},${row*20+10}`).join(' ')" fill="none" stroke="#ffd76c" stroke-width="3"/></svg><figcaption>LINE {{index+1}}</figcaption></figure></div>
  <h3>STAKE & CONTROLS</h3>
  <p>Use −, +, the stake menu or MAX to choose {{(stakeLimits.min/100).toFixed(2)}}–{{(stakeLimits.max/100).toFixed(2)}} credits in {{(stakeLimits.step/100).toFixed(2)}} steps. {{isFishGame(game)?'The stake is per valid hit.':'One stake pays for the complete spin, draw or feature sequence. Fast animation and Show result do not alter the outcome.'}}</p>
  <p>{{staked?'Plays require an online session and enough available credits. Accepted results are saved; reconnecting restores them without charging for a new play.':'Guest previews and free practice do not spend or award credits. The returns above describe the play-credit games.'}}</p>
 </div>
</template>
<style>
.game-rules-button{margin-left:auto;display:flex;align-items:center;gap:8px;padding:10px 18px;border:1px solid #d8b764;border-radius:22px;background:#172732;color:#ffe29d;font-weight:800;cursor:pointer}
.game-rules{font-size:15px;line-height:1.6}.game-rules h3{font-size:13px;letter-spacing:.15em;color:#ffe29d;margin:24px 0 10px}.game-rules li{padding-left:5px;margin:10px 0}.game-rules ol{padding-left:22px}.game-rules .rules-mode{font-size:12px;letter-spacing:.06em;color:#8de4d5}.rules-mode span{color:#bbc6d4}.rules-return{padding:1px 18px 12px;border:1px solid #ae8b4566;border-radius:14px;background:#060c1f80}.game-rules table{width:100%;border-collapse:collapse;text-align:left;font-size:14px}.game-rules td,.game-rules th{padding:10px 6px;border-bottom:1px solid #ffffff20}.rules-lines{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:20px}.rules-lines figure{margin:0;padding:8px;border-radius:8px;background:#080d1c;text-align:center}.rules-lines svg{width:100%;max-width:120px}.rules-lines figcaption{font-size:10px;color:#dbc894}
@media(max-width:600px){.game-rules-button{padding:9px 11px;font-size:12px}.game-rules{font-size:14px}.game-rules table{font-size:12px}.rules-return{padding:1px 12px 10px}}
</style>
