<script setup lang="ts">
import {expansionSymbolNames} from './expansion-theme';
import {computed,onMounted} from 'vue';
import {cabinetGames,cabinetBase,isCabinetGame,cabinetExpansionProfile,reefChallengeProfile,stagingRules,stakeLimits,isFishGame,type StagingGame} from '@new-game/game-math';
import {stage} from './staging-state';
import {loadEnvironment} from './api';
import ArcadeSymbol from './ArcadeSymbol.vue';
const props=defineProps<{game:StagingGame;staked:boolean}>();
const instructions:Record<StagingGame,string[]>={
 'corsair-cove':['Choose one of four deck cannons. Copper sprats and pirate puffers are small; sailfins and octopuses medium; swordfish and anchor crabs large. The spectral captain and ghost galleon are bosses.','Aim along drifting convoys. AUTO, LOCK and FAST use the same approved catch rules as the other fish worlds.'],
 'cosmic-tides':['Choose one of four plasma cannons. Comet minnows and star shrimp are small; jellies and seahorses medium; mantas and nautiluses large. The cosmic leviathan and astral mermaid are bosses.','Lead the creatures through their orbital paths. The wheel pays the existing boss award when caught.'],
 'outlaw-sevens':['Three reels and five lines pay matching triples. See the exact symbol returns below.','The sheriff highlights each winning line after the reels slow to a stop.'],
 'celestial-wilds':['Five reels and nine paylines in a portrait cabinet. Match at least three symbols from the left.','The moon scepter substitutes for any symbol. An all-wild run counts once per line.'],
 'clockwork-vault':['Three gears start locked in the fifteen-cell vault. Three pulses remain.','New gears lock in place and reset the pulse counter. The sequence ends when the board fills or pulses run out.'],
 'phoenix-falls':['Connect groups of at least four matching feathers horizontally or vertically on a 6 × 5 board.','Groups ignite and new feathers fall. Up to six cascades are included in one stake.'],
 'meteor-keno':['Select 4–10 coordinates from 1–80 or choose a constellation preset. Presets only select numbers; they do not improve odds.','Twenty unique meteors reveal. Selected matches count toward the same approved keno return.'],
 'bamboo-keno':['Select 4–10 lanterns from 1–80 or choose a lantern path preset. Presets only select numbers; they do not improve odds.','Twenty unique lantern numbers reveal. Selected matches use the same approved keno return.'],
 'disco-diamonds':['Three reels and five active paylines. Match all three symbols on a line.','Disco diamonds use the gem award. Cherry 1×, bell/BAR 2×, diamond 3× and seven 5×; add all winning lines.'],
 'midnight-express':['An upright five-reel cabinet with nine active paylines. Play in portrait on phones.','The locomotive is WILD. It substitutes in left-to-right runs of at least three symbols. An all-locomotive run pays once on its line.'],
 'pirate-gold':['Center-row doubloons lock their entire reel. The other reels respin up to three times with no extra stake.','Collect all five doubloons for the existing 5× return. New locks do not reset the respin counter.'],
 'sunken-dynasty':['Choose one of four jade cannons. Koi and shrimp are small; lionfish and cuttlefish medium; turtles and sentinel crabs large; the dynasty dragon and sea empress are bosses.','A moving jackpot wheel is a boss target. Shoot and capture it for the existing 20× stake return. Auto, lock and rapid firing work exactly as in Reef Party. AI shots do not add capture attempts.'],
 'polar-odyssey':['Choose a crystal cannon. Icefish and shrimp are small; seals and squid medium; narwhals and snow crabs large; glacial serpents and crystal orcas are bosses.','The moving jackpot wheel can be shot and caught for the existing 20× boss award. Small creatures arrive between larger targets, with one boss at a time.'],
 'neon-numbers':['Choose 4–10 numbers from 1–80. Twenty numbers reveal in sequence. Quick Pick selects six editable numbers.','Uses the same test paytable as Orchard Numbers. There is no separate bonus stake.'],
 'pearl-keno':['Choose 4–10 numbered pearls from 1–80. Twenty pearls reveal. Matching selected pearls are highlighted.','Uses the same test paytable as Orchard Numbers. There is no additional bonus pool.'],
 'abyss-legends':['Choose one of four seats in the Abyss Lounge. Each player controls their own cannon and stake.','Aim, click to fire, or enable AUTO and LOCK. Lantern anglers, leafy seadragons, armored sharks, krakens and leviathans use the same size-based rewards as Reef Party.','A treasure chest is a medium target. Catching it reveals its 3× award. The moving jackpot wheel is itself a boss target: shoot and capture it to win 20× the shot stake. These animations add no extra stake, payout or progressive pool.'],
 'ruby-rush':['Three reels, three rows. Choose your stake and press SPIN. All five paylines are active.','Match all three symbols on a line. Red diamonds use the gem award. The line review highlights each winning path in turn.'],
 'sapphire-crown':['Play in portrait orientation. Choose your stake and press SPIN. All nine paylines are active.','The crown is WILD. It substitutes in left-to-right runs of three or more; an all-crown run pays once on each line.'],
 'solar-fortune':['Five reels show a single row of symbols. A sun coin locks its reel. Choose your stake and press SPIN.','Only unlocked reels respin, up to three times, with no additional stake. New locks do not reset the counter. Collect all five sun coins to win.'],
 'neon-sevens':['Three reels, three rows. Choose your stake, then press SPIN. All five paylines are active.','Match all three symbols on a line. Use LINE MAP to see the five paths.'],
 'jade-fortune':['Choose your stake, then press SPIN. All nine paylines are active.','The dragon is wild and substitutes for any matching symbol. Matches run from the leftmost reel across adjacent reels.'],
 'coin-carnival':['Choose your stake and start a spin. A coin in the middle row locks its whole reel.','The unlocked reels respin up to three times at no additional stake. Collect coins on all five reels to win.'],
 'temple-lights':['Choose your stake and press SPIN. The three horizontal rows are active.','Match three or more of the same symbol on adjacent reels, starting at the left edge.'],
 'aurora-vault':['Play in portrait orientation. Start with three crystals already locked in a 3-column, 5-row vault.','You have three pulses. New crystals stay locked and reset the remaining pulses to three. The sequence ends when the vault is full or no pulses remain.'],
 'ember-relics':['Start a sequence on the 6 × 5 relic board. Groups of four or more matching relics connected horizontally or vertically clear together.','New relics fall into the gaps. The sequence continues until no group remains, with a maximum of six clearing cascades. Diagonal connections do not count.'],
 'orchard-numbers':['Select 4–10 different numbers from 1–80, then press DRAW. Twenty different numbers are drawn.','QUICK PICK selects six numbers you can change. CLEAR removes your selection. A hit is one of your selected numbers appearing in the draw.'],
 'reef-party':['Choose a table and one of four player seats. Aim and click or tap for each shot. Several shots can travel at once; each valid hit uses the cannon stake selected when it was fired.','AUTO keeps firing in your aim direction. LOCK tracks a creature; tap another creature to change targets. FAST doubles the automatic firing cadence. Turning it on does not change capture chances or rewards.','Only a server-validated hit spends credits. Shots that miss, expire, or reach an already-caught creature cost nothing. A resisted hit still spends its stake.','Each valid hit has an independent capture chance. Larger creatures pay more and usually need more hits, but there is no fixed health bar or guaranteed number of shots.','Treasure chests use the medium tier (3×); the moving jackpot wheel is a boss target with the existing 20× catch award. There is no additional wheel stake or jackpot pool.','Auto fire stops when you pause, leave the table, change stake, lose connection, or have insufficient credits. Catch celebrations show the existing award; there is no separate progressive jackpot.']
};
const lines=computed(()=>isCabinetGame(props.game)?cabinetGames[props.game].lines:props.game==='temple-lights'?[[0,0,0,0,0],[1,1,1,1,1],[2,2,2,2,2]]:[]);
const cabinet=computed(()=>isCabinetGame(props.game)?cabinetGames[props.game]:null);
const baseGame=computed(()=>isCabinetGame(props.game)?cabinetBase(props.game):null);
const themed=computed(()=>Object.hasOwn(cabinetExpansionProfile.rules,props.game));
function symbolName(symbol:string){if(expansionSymbolNames[props.game]?.[symbol])return expansionSymbolNames[props.game][symbol];if(props.game==='midnight-express')return ({dragon:'Locomotive · WILD',coin:'Ticket',lotus:'Pocket watch',gem:'Sapphire',bell:'Whistle',leaf:'Luggage',seven:'Lantern'} as Record<string,string>)[symbol];if(props.game==='pirate-gold')return ({coin:'Doubloon · HOLD',cherry:'Compass',bell:'Skull',bar:'Ship',seven:'Treasure map'} as Record<string,string>)[symbol];if(props.game==='disco-diamonds'&&symbol==='gem')return 'Disco diamond';if(props.game==='sapphire-crown')return ({dragon:'Crown · WILD',coin:'Sun coin',lotus:'Crystal lotus',gem:'Amethyst',bell:'Scepter',leaf:'Treasure pouch',seven:'Star'} as Record<string,string>)[symbol];if(props.game==='solar-fortune')return ({coin:'Sun coin · HOLD',cherry:'Planet',bell:'Moon',bar:'Star',seven:'Phoenix'} as Record<string,string>)[symbol];return symbol==='gem'&&themed.value?'Ruby':symbol.toUpperCase();}
function returns(symbol:string,count:number){return baseGame.value==='neon-sevens'?({cherry:1,bell:2,bar:2,gem:3,seven:5}[symbol]||0)*({3:1,4:2,5:4}[count]||0):({3:2,4:4,5:8}[count]||0);}
const matchCounts=computed(()=>cabinet.value?.columns===3?[3]:[3,4,5]);
const tiers=Object.values(reefChallengeProfile.tiers);
onMounted(()=>{if(props.staked)void loadEnvironment().catch(()=>{});});
</script>
<template>
 <div class="game-rules">
  <p class="rules-mode">{{staked?'PLAY CREDITS':'GUEST / FREE PREVIEW'}} <span>• No cash or prizes of value</span></p>
  <h3>HOW TO PLAY</h3>
  <ol><li v-for="instruction in instructions[game]" :key="instruction">{{instruction}}</li></ol>
  <section class="rules-return"><h3>{{isFishGame(game)?'CREATURE RETURNS':'WINNING RETURNS'}}</h3>
   <template v-if="isFishGame(game)">
    <p>Each valid paid hit gets one independent capture attempt, with no free solo assists. When you are the only human, three labeled AI crew fire at their own targets. Their hit combos require 8 small, 14 medium, 24 large or 40 boss hits to earn that AI 10, 30, 80 or 200 scoreboard points. A 12-second gap resets the combo. AI points have no credit value and do not remove shared creatures or change your awards. The crew stop when another human joins.</p><table><thead><tr><th>Size</th><th>Return</th><th>Capture per paid hit</th><th>Average hits per catch</th></tr></thead><tbody><tr v-for="tier in tiers" :key="tier.label"><th>{{tier.label}}</th><td>{{tier.multiplier}}× stake</td><td>{{tier.captureTickets/100}}%</td><td>{{(10000/tier.captureTickets).toFixed(1)}}</td></tr></tbody></table>
    <p>At a 0.25 stake, a successful small, medium, large or boss catch returns 0.25, 0.75, 2.00 or 5.00 credits respectively. Open SPECIES at the table to see each creature’s size tier.</p>
   </template>
   <template v-else><p>{{stagingRules[game]}}</p><p v-if="staked&&stage.roundPolicy"><strong>Current chance of any credit return: {{stage.roundPolicy.payingPercent}}%.</strong> Applies equally to all players in independent rounds; no fixed win schedule. A return can be smaller than the stake. This is not RTP or a guarantee for a short session. Revision {{stage.roundPolicy.revision}} applies to new rounds; saved results retain their original rules.</p></template>
   <p>Multipliers apply to the total selected stake. Returns include any returned stake; they are not extra profit on top of it. An unsuccessful paid play returns zero.</p>
  </section>
  <table v-if="cabinet && baseGame!=='coin-carnival'" class="symbol-paytable"><thead><tr><th>Symbol</th><th v-for="count in matchCounts" :key="count">{{count}}</th></tr></thead><tbody><tr v-for="symbol in cabinet.symbols" :key="symbol"><th><ArcadeSymbol :symbol="symbol" :theme="game"/><span>{{symbolName(symbol)}}</span></th><td v-for="count in matchCounts" :key="count">{{returns(symbol,count)}}×</td></tr></tbody></table>
  <div v-if="lines.length" class="rules-lines" aria-label="Active payline paths"><figure v-for="(line,index) in lines" :key="index"><svg :viewBox="`0 0 ${line.length*20} 60`" role="img" :aria-label="`Line ${index+1}: rows ${line.map(row=>row+1).join(', ')}`"><path :d="`M0 20H${line.length*20}M0 40H${line.length*20}`" stroke="#ffffff25" fill="none"/><polyline :points="line.map((row,col)=>`${col*20+10},${row*20+10}`).join(' ')" fill="none" stroke="#ffd76c" stroke-width="3"/></svg><figcaption>LINE {{index+1}}</figcaption></figure></div>
  <p>The lobby groups settled returns as Minor below 5× stake, Major from 5× to below 20×, and Jackpot from 20×. These groups do not add another payout or a progressive pool. The lobby totals add your settled returns in each tier and show your total wagered. They include returned stakes, exclude grants and daily-wheel awards, and do not form a separate prize pool.</p>
  <h3>STAKE & CONTROLS</h3>
  <p>Use −, +, the stake menu or MAX to choose {{(stakeLimits.min/100).toFixed(2)}}–{{(stakeLimits.max/100).toFixed(2)}} credits in {{(stakeLimits.step/100).toFixed(2)}} steps. {{isFishGame(game)?'The stake is per valid hit.':'One stake pays for the complete spin, draw or feature sequence. Fast animation and Show result do not alter the outcome.'}}</p>
  <p>{{staked?'Plays require an online session and enough available credits. Accepted results are saved; reconnecting restores them without charging for a new play.':'Guest previews and free practice do not spend or award credits. The returns above describe the play-credit games.'}}</p>
 </div>
</template>
<style>
.game-rules-button{margin-left:auto;display:flex;align-items:center;gap:8px;padding:10px 18px;border:1px solid #d8b764;border-radius:22px;background:#172732;color:#ffe29d;font-weight:800;cursor:pointer}
.game-rules{font-size:15px;line-height:1.6}.game-rules h3{font-size:13px;letter-spacing:.15em;color:#ffe29d;margin:24px 0 10px}.game-rules li{padding-left:5px;margin:10px 0}.game-rules ol{padding-left:22px}.game-rules .rules-mode{font-size:12px;letter-spacing:.06em;color:#8de4d5}.rules-mode span{color:#bbc6d4}.rules-return{padding:1px 18px 12px;border:1px solid #ae8b4566;border-radius:14px;background:#060c1f80}.game-rules table{width:100%;border-collapse:collapse;text-align:left;font-size:14px}.game-rules td,.game-rules th{padding:10px 6px;border-bottom:1px solid #ffffff20}.rules-lines{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:20px}.rules-lines figure{margin:0;padding:8px;border-radius:8px;background:#080d1c;text-align:center}.rules-lines svg{width:100%;max-width:120px}.rules-lines figcaption{font-size:10px;color:#dbc894}
@media(max-width:600px){.game-rules-button{padding:9px 11px;font-size:12px}.game-rules{font-size:14px}.game-rules table{font-size:12px}.rules-return{padding:1px 12px 10px}}
</style>
