import {describe,it,expect} from 'vitest';
import {blackjackShoe,blackjackDeal,blackjackAct,blackjackFinish,blackjackPublic,blackjackCost,handValue,storyboardRandom,fishGames,fishGuide,reefTier,reefTarget,reefLeadAngle,reefFlight,stagingOutcome,stagingMultiplier,stagingGameProfileId} from '@new-game/game-math';
import {catalog,premiumGames} from '@new-game/contracts';
const shoe=(...ranks:number[])=>[...ranks,...Array(100).fill(10)].map((rank,i)=>({rank,suit:i%4}));
describe('approved six-deck blackjack',()=>{
 it('shuffles all 312 cards with exactly six of every rank and suit',()=>{const a=blackjackShoe(storyboardRandom(987)),b=blackjackShoe(storyboardRandom(988));expect(a).not.toEqual(b);for(let rank=1;rank<=13;rank++)for(let suit=0;suit<4;suit++)expect(a.filter(c=>c.rank===rank&&c.suit===suit)).toHaveLength(6);});
 it('values soft aces and face cards correctly',()=>{expect(handValue(shoe(1,1,9).slice(0,3))).toEqual({total:21,soft:true});expect(handValue(shoe(1,1,9,13).slice(0,4))).toEqual({total:21,soft:false});});
 it('pays natural 3:2 and pushes two naturals with exact half-credit stakes',()=>{const natural=blackjackDeal(50,shoe(1,9,13,8));expect(natural.award).toBe(125);expect(natural.settled).toBe(true);expect(blackjackDeal(50,shoe(1,1,13,12)).award).toBe(50);expect(blackjackDeal(50,shoe(10,1,9,13)).award).toBe(0);});
 it('stands on soft 17; ordinary 21 pays 1:1 and equal totals push',()=>{const a=blackjackAct(blackjackDeal(50,shoe(10,1,8,6)),'STAND');expect(a.dealer).toHaveLength(2);expect(a.award).toBe(100);expect(blackjackAct(blackjackDeal(50,shoe(10,9,8,9)),'STAND').award).toBe(50);expect(blackjackAct(blackjackDeal(50,shoe(10,10,5,7,6)),'HIT').award).toBe(100);});
 it('doubles the stake for exactly one card and does not mutate the previous receipt',()=>{const start=blackjackDeal(2000,shoe(5,10,6,7,10)),a=blackjackAct(start,'DOUBLE');expect(blackjackCost(a)).toBe(4000);expect(a.award).toBe(8000);expect(a.hands[0].cards).toHaveLength(3);expect(start.hands[0].cards).toHaveLength(2);expect(()=>blackjackAct(a,'HIT')).toThrow();});
 it('allows only one same-rank split, supports double after split, caps exposure at 80',()=>{let a=blackjackDeal(2000,shoe(8,10,8,7,3,2,10,10));a=blackjackAct(a,'SPLIT');expect(blackjackPublic(a).actions).not.toContain('SPLIT');a=blackjackAct(a,'DOUBLE');expect(a.active).toBe(1);a=blackjackAct(a,'DOUBLE');expect(blackjackCost(a)).toBe(8000);expect(a.award).toBe(16000);expect(()=>blackjackAct(blackjackDeal(50,shoe(10,10,13,7)),'SPLIT')).toThrow();});
 it('split aces get one card each and a split 21 is an ordinary win',()=>{const a=blackjackAct(blackjackDeal(50,shoe(1,9,1,8,10,10)),'SPLIT');expect(a.settled).toBe(true);expect(a.award).toBe(200);expect(a.hands.every(h=>h.cards.length===2&&h.result==='WIN')).toBe(true);});
 it('hides the shoe and dealer hole card until settlement, auto-standing is deterministic',()=>{const a=blackjackDeal(50,shoe(10,6,8,10,10));const publicHand=blackjackPublic(a);expect(publicHand.dealer).toEqual([a.dealer[0],null]);expect(publicHand).not.toHaveProperty('shoe');expect(publicHand).not.toHaveProperty('cursor');expect(publicHand.dealerValue).toBeNull();expect(blackjackFinish(structuredClone(a))).toEqual(blackjackAct(a,'STAND'));});
 it('rejects off-step stakes and unavailable moves',()=>{for(const stake of [0,25,75,2025,2050])expect(()=>blackjackDeal(stake,shoe(10,7,5,9))).toThrow();const a=blackjackAct(blackjackDeal(50,shoe(2,7,3,9,4)),'HIT');expect(()=>blackjackAct(a,'DOUBLE')).toThrow();});
});
describe('premium collection',()=>{
 it('lists six distinct fish worlds and five keno games with production play still gated',()=>{expect(catalog.filter(g=>g.category==='Fish')).toHaveLength(6);expect(catalog.filter(g=>g.category==='Keno')).toHaveLength(5);expect(premiumGames).toEqual(['royal-blackjack','double-deck-blackjack','european-blackjack']);expect(catalog).toHaveLength(30);});
 it('new fish species have all four tiers and collidable scheduled trajectories',()=>{for(const game of fishGames.slice(2)){expect(new Set(fishGuide(game).map(reefTier)).size).toBe(4);for(const species of fishGuide(game)){const id=Array.from({length:80},(_,i)=>i+1).find(id=>reefTarget(id,0,game).species===species)!;const target=reefTarget(id,0,game),at=target.spawnAt+15;expect(reefFlight(1,reefLeadAngle(1,id,at,game),at,[id],game).targetId).toBe(id);}}});
 it('keno variants reproduce the approved Orchard draw and award for each seed',()=>{for(const game of ['neon-numbers','pearl-keno'] as const){expect(stagingGameProfileId(game)).toBe('stage-keno-cabinets-v1');for(let n=4;n<=10;n++)for(let seed=0;seed<40;seed++){const picks=Array.from({length:n},(_,i)=>i+1),base=stagingOutcome('orchard-numbers','same',storyboardRandom(seed),picks),next=stagingOutcome(game,'same',storyboardRandom(seed),picks);expect(next.drawn).toEqual(base.drawn);expect(stagingMultiplier(next)).toBe(stagingMultiplier(base));}}});
});
